Trevorwhitney/add trivy
grafana/loki pull request #10231
Opened 2023-08-11 18:35 UTC by trevorwhitney

`trivy` is a command line utility that can scan our images for vulnerabilities. For example, this is how I checked #10217 addressed the CVEs we were hoping it would

```
❯ trivy i grafana/loki:release-2.8.x-d784431
2023-08-11T12:34:15.272-0600    INFO    Vulnerability scanning is enabled
2023-08-11T12:34:15.272-0600    INFO    Secret scanning is enabled
2023-08-11T12:34:15.272-0600    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-08-11T12:34:15.272-0600    INFO    Please see also https://aquasecurity.github.io/trivy/dev/docs/scanner/secret/#recommendation for faster secret detection
2023-08-11T12:34:15.283-0600    INFO    Detected OS: alpine
2023-08-11T12:34:15.283-0600    INFO    Detecting Alpine vulnerabilities...
2023-08-11T12:34:15.286-0600    INFO    Number of language-specific files: 1
2023-08-11T12:34:15.286-0600    INFO    Detecting gobinary vulnerabilities...

grafana/loki:release-2.8.x-d784431 (alpine 3.18.2)

Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 6, HIGH: 0, CRITICAL: 0)

┌────────────┬───────────────┬──────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability │ Severity │ Installed Version │ Fixed Version │                            Title                            │
├────────────┼───────────────┼──────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────────┤
│ libcrypto3 │ CVE-2023-2975 │ MEDIUM   │ 3.1.1-r1          │ 3.1.1-r2      │ AES-SIV cipher implementation contains a bug that causes it │
│            │               │          │                   │               │ to ignore empty...                                          │
│            │               │          │                   │               │ https://avd.aquasec.com/nvd/cve-2023-2975                   │
│            ├───────────────┤          │                   ├───────────────┼─────────────────────────────────────────────────────────────┤
│            │ CVE-2023-3446 │          │                   │ 3.1.1-r3      │ Excessive time spent checking DH keys and parameters        │
│            │               │          │                   │               │ https://avd.aquasec.com/nvd/cve-2023-3446                   │
│            ├───────────────┤          │                   ├───────────────┼─────────────────────────────────────────────────────────────┤
│            │ CVE-2023-3817 │          │                   │ 3.1.2-r0      │ Excessive time spent checking DH q parameter value          │
│            │               │          │                   │               │ https://avd.aquasec.com/nvd/cve-2023-3817                   │
├────────────┼───────────────┤          │                   ├───────────────┼─────────────────────────────────────────────────────────────┤
│ libssl3    │ CVE-2023-2975 │          │                   │ 3.1.1-r2      │ AES-SIV cipher implementation contains a bug that causes it │
│            │               │          │                   │               │ to ignore empty...                                          │
│            │               │          │                   │               │ https://avd.aquasec.com/nvd/cve-2023-2975                   │
│            ├───────────────┤          │                   ├───────────────┼─────────────────────────────────────────────────────────────┤
│            │ CVE-2023-3446 │          │                   │ 3.1.1-r3      │ Excessive time spent checking DH keys and parameters        │
│            │               │          │                   │               │ https://avd.aquasec.com/nvd/cve-2023-3446                   │
│            ├───────────────┤          │                   ├───────────────┼─────────────────────────────────────────────────────────────┤
│            │ CVE-2023-3817 │          │                   │ 3.1.2-r0      │ Excessive time spent checking DH q parameter value          │
│            │               │          │                   │               │ https://avd.aquasec.com/nvd/cve-2023-3817                   │
└────────────┴───────────────┴──────────┴───────────────────┴───────────────┴─────────────────────────────────────────────────────────────┘
```

This PR adds that command as `Makefile` target, as well as adding the `trivy` binary to our drone build image so we can add it to our pipelines in the future.

2023-08-11 18:44 UTC, poyzannur approved these changes
thanks so much for incorporating this!

2023-08-21 14:28 UTC, chaudum requested changes

2023-08-21 14:28 UTC, chaudum commented on .drone/drone.yml
> -...
Signature got removed

2023-08-23 17:52 UTC, trevorwhitney commented on .drone/drone.yml
> -...
good catch, will fix

2023-08-23 21:49 UTC, trevorwhitney commented
@chaudum fixed

2023-08-24 17:50 UTC, chaudum approved these changes

2023-08-24 17:52 UTC, merged