Stopped String() from doubly escaping regex characters
grafana/loki pull request #10277
Opened 2023-08-16 22:48 UTC by akhilanarayanan

**What this PR does / why we need it**:
When queries have regex, characters that needed escaping were escaped twice. Now they're only singly escaped. This is good because it reduces the character count so users can submit queries closer to the 5120 byte limit.

**Which issue(s) this PR fixes**:
Sort of addresses #10153

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
  - [ ] If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)

2023-08-16 22:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=10277) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=10277) before we can accept your contribution.<br/><hr/>**Akhila Narayanan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=10277) it.</sub>

2023-08-17 21:34 UTC, MasslessParticle requested changes

2023-08-17 21:34 UTC, MasslessParticle commented on pkg/logql/syntax/parser_test.go
> +	require.True(t, len(query) < 5120)
Why are you checking this length here?

2023-08-17 21:34 UTC, MasslessParticle commented on pkg/logql/syntax/parser_test.go
> +	// need to change some backticks to "
Is this comment relevant?

2023-08-17 21:34 UTC, MasslessParticle commented on pkg/logql/syntax/parser_test.go
> +	query = `sum(rate({cluster="beep", namespace="boop"} | msg=~` + `"` + `.*?(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS) /loki/api/(?i)(\d+[a-z]|[a-z]+\d)\w*/query_range` + `"` + `[1d]))`
I don’t think we need to redefine `query` here

2023-08-17 21:34 UTC, MasslessParticle commented
Nice work! Just some test cleanup and this can be merged

2023-08-17 22:01 UTC, akhilanarayanan commented on pkg/logql/syntax/parser_test.go
> +	require.True(t, len(query) < 5120)
good point. length check can go

2023-08-18 17:40 UTC, MasslessParticle approved these changes
LGTM, nice work

2023-08-18 17:55 UTC, merged