[release-2.9.x] Deprecate ruler setting with misleading name
grafana/loki pull request #10328
Opened 2023-08-23 15:49 UTC by grafanabot

Backport e3b25fb36c11f5c3ecdc9b81af38ddd79db912f1 from #10322

---

**What this PR does / why we need it**:

The setting defaults to 0s and is not supposed to be changed, therefore it can be removed in a future version (e.g. 3.0) of Loki.

2023-08-23 16:21 UTC, chaudum requested changes

2023-08-23 16:21 UTC, chaudum commented on CHANGELOG.md
> +* [10295](https://github.com/grafana/loki/pull/10295) **changhyuni**: Storage: remove signatureversionv2 from s3.
That line does not belong to this PR

2023-08-24 07:21 UTC, MichelHollands approved these changes

2023-08-29 18:37 UTC, chaudum approved these changes

2023-08-29 18:39 UTC, merged