Update Getting Started topic and graphics
grafana/loki pull request #11350
Opened 2023-11-30 23:07 UTC by JStickler

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Final PR to complete fixes #9228 

**Special notes for your reviewer**:
Updates Getting Started topic to be a general overview
Adds new Quick Start topic for running Loki Docker compose file locally
Adds three new graphics
Removes two unused graphics

2023-12-04 12:29 UTC, monodot requested changes
I've made some suggestions based on running through the examples. I think we should update the metric query to ensure it draws a single metric line on a graph, and also update the Docker Compose setup so that Flog writes more lines per second, which will make the chart more meaningful and so easier to understand for first-timers.

2023-12-12 15:53 UTC, monodot approved these changes
Great, this looks good to me.

2023-12-12 16:04 UTC, MichelHollands approved these changes
Nice. I left 1 question but looking fine otherwise.

2023-12-12 16:04 UTC, MichelHollands commented on docs/sources/get-started/quick-start.md
> +If you want to experiment with Loki, you can run Loki locally using the Docker Compose file that ships with Loki. It runs Loki in a [scalable monolithic deployment](https://grafana.com/docs/loki/late
Is that URL correct? Doesn't it point to the SSD version instead of the monolithic one?

2023-12-12 17:00 UTC, merged