test: Detected Labels tests and minor improvements
grafana/loki pull request #12505
Opened 2024-04-08 12:44 UTC by shantanualsi

**What this PR does / why we need it**:

This PR adds some missing unit tests to the detected labels endpoint. 

**Which issue(s) this PR fixes**:
NA

2024-04-11 09:47 UTC, MichelHollands approved these changes

2024-04-12 14:04 UTC, trevorwhitney requested changes
I did a review of both these PRs in #12441, and I included a lot of feedback on the tests in that review. Would you mind bringing over the relevant feedback from that review to this PR?

2024-04-12 14:05 UTC, shantanualsi commented
@trevorwhitney yes thank you so much! I'll have a look at https://github.com/grafana/loki/pull/12441 and apply the suggestions here as well!

2024-04-19 08:45 UTC, shantanualsi commented
closing this PR as all these changes are merged in https://github.com/grafana/loki/pull/12441 along with PR comments.

2024-04-19 08:45 UTC, closed without merging