docs: add missing aliases for moved pages
grafana/loki pull request #12580
Opened 2024-04-11 17:41 UTC by JStickler

**What this PR does / why we need it**:
I realized that I'd moved/renamed these pages and not included the aliases for redirects.

2024-04-11 18:01 UTC, jdbaldry reviewed
Ah, it looks like `doc-validator` is mean because it doesn't know that those headings are gonna come in from the shared file. I can fix this tomorrow.

2024-04-11 18:02 UTC, jdbaldry reviewed
I think I've already added the alias into this file?

2024-04-11 18:33 UTC, JStickler commented
>https://grafana.com/docs/loki/latest/operations/storage/retention/

Did you just update the branch?  I pulled from main, and it didn't have an alias.  ¯\_(ツ)_/¯

2024-04-12 08:46 UTC, jdbaldry requested changes

2024-04-12 11:50 UTC, JStickler commented on docs/sources/configure/storage.md
> +  - /docs/loki/latest/storage/
OMG, it's just at the top of the metadata instead of at the bottom, where I usually put them.  D'oh!
I'll fix it, thanks.

2024-04-12 12:01 UTC, jdbaldry approved these changes
LGTM, thanks for fixing :)

2024-04-12 12:06 UTC, merged