fix: skipping label if it contains special symbol
grafana/loki pull request #14068
Opened 2024-09-06 08:26 UTC by ravishankar15

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #13963 

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

2024-09-09 08:50 UTC, vlad-diachenko requested changes
looks great, however, we need to address some small things to get it merged

2024-09-09 08:50 UTC, vlad-diachenko commented on pkg/logql/log/parser.go
> +			return -1
it's necessary to replace it with ` ` (whitespace) instead of skipping it

2024-09-09 08:50 UTC, vlad-diachenko commented on pkg/logql/log/parser.go
> +	res = strings.Map(removeInvalidUtf, res)
see:  https://github.com/grafana/loki/pull/14068#issuecomment-2337504002
```suggestion
	if strings.ContainsRune(source, utf8.RuneError) {
		res = strings.Map(removeInvalidUtf, res)
	}
```

2024-09-09 08:50 UTC, vlad-diachenko commented on pkg/logql/log/parser.go
> +	removeInvalidUtf := func(r rune) rune {
nit: please move this function outside of `unescapeJSONString` function to re-use it in logfmt parser ...

2024-09-09 08:50 UTC, vlad-diachenko commented on pkg/logql/log/parser.go
> +		removeInvalidUtf := func(r rune) rune {
nit: can be re-used from json parse

2024-09-09 08:50 UTC, vlad-diachenko commented on pkg/logql/log/parser.go
> +		val = bytes.Map(removeInvalidUtf, val)
see: https://github.com/grafana/loki/pull/14068#issuecomment-2337504002
```suggestion
		if bytes.ContainsRune(source, utf8.RuneError) {
			val = bytes.Map(removeInvalidUtf, val)
		}
```

2024-09-09 13:57 UTC, ravishankar15 commented
@vlad-diachenko Thanks for the insights :) I have made the suggestion

2024-09-10 09:22 UTC, vlad-diachenko approved these changes
looks awesome 💎 🥇 huge thanks for the contribution @ravishankar15

2024-09-10 11:10 UTC, merged