chore: Fix promtail local config
grafana/loki pull request #14259
Opened 2024-09-25 12:38 UTC by LashaJini

**What this PR does / why we need it**:

According to [Build and run from source](https://github.com/grafana/loki/tree/main/production#build-and-run-from-source) `promtail` should start without issues, however, there are missing fields on the `promtail-local-config.yaml` file.

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

2024-09-25 12:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=14259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=14259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=14259) it.</sub>

2024-09-25 12:42 UTC, LashaJini commented on clients/cmd/promtail/promtail-local-config.yaml
> +  log_level: debug
https://github.com/grafana/loki/blob/main/clients/cmd/promtail/main.go#L106

2024-09-25 12:42 UTC, LashaJini commented on clients/cmd/promtail/promtail-local-config.yaml
> +  sync_period: 10s
https://github.com/grafana/loki/blob/main/clients/pkg/promtail/positions/positions.go#L154

2024-09-25 12:42 UTC, LashaJini commented on clients/cmd/promtail/promtail-local-config.yaml
> +  sync_period: 10s
https://github.com/grafana/loki/blob/main/clients/pkg/promtail/targets/file/filetarget.go#L210

2024-09-30 22:50 UTC, trevorwhitney requested changes
Thanks for the contribution. Can you share the error you recieved? I was able to start up without problem using this config locally. Some of the configs you're setting we have defaults for, for example [log level](https://github.com/grafana/loki/blob/4d6992982d99a542f1e99af18b691830b71469e0/vendor/github.com/grafana/dskit/log/level.go#L35)

2024-10-03 08:45 UTC, LashaJini commented
> Thanks for the contribution. Can you share the error you recieved? I was able to start up without problem using this config locally. Some of the configs you're setting we have defaults for, for example [log level](https://github.com/grafana/loki/blob/4d6992982d99a542f1e99af18b691830b71469e0/vendor/github.com/grafana/dskit/log/level.go#L35)

with current config:
![Screenshot from 2024-10-03 12-43-30](https://github.com/user-attachments/assets/e69e1c3e-4759-4b98-b0bc-208c54bd2638)

According to [docs](https://github.com/grafana/loki/tree/main/production#build-and-run-from-source), passing the config file only, should be sufficient to start `promtail`

2024-10-03 17:08 UTC, trevorwhitney commented
you're using two different config paths in that example. `cmd/promtail/promtail-local-config.yaml` in the first screenshot should be `clients/cmd/promtail/promtail-local-config.yaml`

2024-10-03 18:05 UTC, LashaJini commented
> you're using two different config paths in that example. `cmd/promtail/promtail-local-config.yaml` in the first screenshot should be `clients/cmd/promtail/promtail-local-config.yaml`

My bad, wrong screenshot.

2024-10-03 18:45 UTC, trevorwhitney commented
Got it, thanks for the update, I was able to re-create. Thanks for offering a fix, but I think we should fix the code instead of just adding a band-aid to the config file. I spent a little time looking at this and I'm not sure why the level config is empty when we check it. We are definitely calling `.RegisterFlags` on it, which sets the level to info, so this seems like a regression to me.

2024-10-03 21:54 UTC, LashaJini commented
Let me know if we should close the PR and open a new one. Meanwhile I can also look into it later :+1:

2024-10-04 16:40 UTC, cstyan commented
> Got it, thanks for the update, I was able to re-create. Thanks for offering a fix, but I think we should fix the code instead of just adding a band-aid to the config file. I spent a little time looking at this and I'm not sure why the level config is empty when we check it. We are definitely calling `.RegisterFlags` on it, which sets the level to info, so this seems like a regression to me.

I was thinking the same recently, I think maybe https://github.com/grafana/loki/pull/13719/files is the cause of this as it might have changed how default values for some config structs are applied.

2024-10-04 17:24 UTC, LashaJini commented
> > Got it, thanks for the update, I was able to re-create. Thanks for offering a fix, but I think we should fix the code instead of just adding a band-aid to the config file. I spent a little time looking at this and I'm not sure why the level config is empty when we check it. We are definitely calling `.RegisterFlags` on it, which sets the level to info, so this seems like a regression to me.
> 
> I was thinking the same recently, I think maybe https://github.com/grafana/loki/pull/13719/files is the cause of this as it might have changed how default values for some config structs are applied.

Just tested it. Commented out the whole `UnmarshalYAML` method, rebuilt `promtail` and works without any modification to the original config file :+1:

2024-10-07 08:49 UTC, fgouteroux commented
> @fgouteroux looks like #13719 may have introduced a regression here, thoughts on a fix?

I think its is caused by: https://github.com/grafana/loki/blob/main/clients/pkg/promtail/config/config.go#L45 this is why there is default config var in https://github.com/prometheus/prometheus/blob/main/config/config.go#L146.

That explain why any default value from flag are not kept after UnmarshalYAML func.

2024-10-07 17:03 UTC, cstyan commented
> > @fgouteroux looks like #13719 may have introduced a regression here, thoughts on a fix?
> 
> I think its is caused by: https://github.com/grafana/loki/blob/main/clients/pkg/promtail/config/config.go#L45 this is why there is default config var in https://github.com/prometheus/prometheus/blob/main/config/config.go#L146.
> 
> That explain why any default value from flag are not kept after UnmarshalYAML func.


The second link you gave was to Prometheus code, so it's not relevant to the issue reported here. For Loki and Promtail we use default values via our CLI arguments, so there were default values that were being overwritten by the `UnmarshalYAML` function. #14408 fixes the proble, so this PR shouldn't be necessary anymore.

@LashaJini let us know if you still see any similar problems.

2024-10-07 17:07 UTC, fgouteroux commented
oh I miss this line 😂

2024-10-07 17:12 UTC, LashaJini commented
> > > @fgouteroux looks like #13719 may have introduced a regression here, thoughts on a fix?
> > 
> > 
> > I think its is caused by: https://github.com/grafana/loki/blob/main/clients/pkg/promtail/config/config.go#L45 this is why there is default config var in https://github.com/prometheus/prometheus/blob/main/config/config.go#L146.
> > That explain why any default value from flag are not kept after UnmarshalYAML func.
> 
> The second link you gave was to Prometheus code, so it's not relevant to the issue reported here. For Loki and Promtail we use default values via our CLI arguments, so there were default values that were being overwritten by the `UnmarshalYAML` function. #14408 fixes the proble, so this PR shouldn't be necessary anymore.
> 
> @LashaJini let us know if you still see any similar problems.

Awesome. Then it's just a matter of doc update. We can merge now :+1:

2024-10-18 18:23 UTC, trevorwhitney approved these changes
lgtm

2024-10-18 18:23 UTC, merged