Feat: Add kubeVersionOverride for Helm chart
grafana/loki pull request #14434
Opened 2024-10-09 10:25 UTC by mcastellin

**What this PR does / why we need it**:

With this change is now possible to override the
`.Capabilities.KubeVersion.Version` parameter with a fixed Kubernetes version using `kubeVersionOverride` in values.yaml file.

Overriding the kubeVersion allows chart's user to generate templates from the chart that can be deployed to cluster that are not directly accessible from the user's CLI and run a different Kubernetes version.

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

2024-10-09 10:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=14434) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=14434) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=14434) it.</sub>

2024-10-17 19:37 UTC, trevorwhitney requested changes
This feels like a case for post-processing (ie. modifying rendered templates for different clusters). What becomes the default behavior with this change? When `kubeVersionOverride` is null, does it fall back to `.Capabilities.KubeVersion.Version`? I'm not seeing where that is happening (but I also only took a very quick glance at this).

2024-10-18 06:29 UTC, mcastellin commented
> This feels like a case for post-processing (ie. modifying rendered templates for different clusters). What becomes the default behavior with this change? When `kubeVersionOverride` is null, does it fall back to `.Capabilities.KubeVersion.Version`? I'm not seeing where that is happening (but I also only took a very quick glance at this).

Hello @trevorwhitney, yes, you are correct indeed, when the `kubeVersionOverride` is `null` the value of `loki.kubeVersion` falls back to `.Capabilities.KubeVersion.Version` and it's implemented [here](https://github.com/mcastellin/loki/blob/feat/helm-kubeversion-override/production/helm/loki/templates/_helpers.tpl#L545). This approach is already implemented for other grafana products like Mimir ([see here](https://github.com/grafana/mimir/blob/2bcd169a060c97866d68057664016cab1bec3997/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L402) for instance). The `null` default value ensures backward compatibility with existing values files.

This is a very important feature to have for anyone that manages infrastructure with ArgoCD and needs to deploy helm charts. Charts are not applied directly by Argo, they're first inflated using `helm template`, hence pseudo-parameters such as `.Capabilities.KubeVersion.Version` are not resolved against the target k8s cluster and will default to, I think, v1.16.

Post-processing the templates as you suggested is an option, though resources are generated by the chart based on many conditions (kube version of the target cluster, variables, ..) so even the tiniest change to the `values.yaml` could result in new resources to appear in the rendered template and could be come a nightmare to maintain.

2024-10-21 08:23 UTC, mcastellin commented
> sorry for the cursory initial review, thanks for pointing out the default and similar behavior with mimir. I'm good with this as long as it doesn't affect the default, which is apparently the case. thanks!

No worries @trevorwhitney, I can see you have a lot on your plate 🙂 
I've updated the PR with the generated docs.

2024-10-21 16:13 UTC, merged