chore(block-builder): refactor blockbuilder to use kafka clients directly
grafana/loki pull request #15433
Opened 2024-12-17 05:44 UTC by ashwanthgoli

**What this PR does / why we need it**:

Currently block builders create ephemeral partition reader for processing a new job, but this fails to work as expected because of duplicate kprom metric registration that is triggered on new client creation. We could get around this by wrapping the registerer with `partition_id` and `worker_id` labels and carefully deregistering them when the job processing is complete.

But at this point of time, I prefer directly using the kafka clients (one per each block builder worker) which offers better control over addition/removal of partitions to consume. We can look into partition reader refactor down the line if it's neccessary.

This pr updates block builder to use direct kafka clients, one client per worker. We add partition consume offset when we start a job and remove it at the end of the job to allow reusing the same client.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

2024-12-17 13:04 UTC, ashwanthgoli commented on pkg/blockbuilder/builder/builder.go
> +		converted := make([]AppendInput, 0, fs.NumRecords())
definitely! i'll take that in a follow-up :)

2024-12-17 13:09 UTC, ashwanthgoli commented on pkg/blockbuilder/builder/builder.go
> +			continue
this is unlikely, but if we are already caught-up to the latest produced offset this should allow a few retries before failing. I don't have a strong opinion about this change

2024-12-27 17:10 UTC, owen-d requested changes
I'm not sure this is a net gain

> We could get around this by wrapping the registerer with partition_id and worker_id labels and carefully deregistering them when the job processing is complete.

We could also just pass the metrics structs to the constructors, which seems like a much less invasive change without tricky downsides.


Unfortunately, passing the client directly as done in this PR:
* ~introduces stateful mutation of offset tracking (`AddConsumePartitions` and cleanup after a job finishes). This will result in some tricky issues if/when we try to process multiple jobs from the same partitions simultaneously~ edit: nvm, this isn't valid since you're creating a client per worker.
* Breaks out of the library we're currently using between both kafka reader impls

edit:
I'm having trouble figuring out where the panic comes from. In main, the readerFactory reuses the same metrics structs which are ultimately initialized in modules.go

If I'm missing something here, feel free to dismiss this review

2024-12-30 05:17 UTC, ashwanthgoli commented
> I'm having trouble figuring out where the panic comes from. The readerFactory reuses the same metrics structs which are ultimately initialized once in modules.go

that's right, but we do not register the kprom [metrics](https://github.com/grafana/loki/blob/5bec7d2221e6cc14cf0969057a0f3447d708b753/pkg/kafka/partition/reader.go#L88C3-L88C8) present in this struct unlike the other entries. kprom metrics configured as [client opts](https://github.com/grafana/loki/blob/5bec7d2221e6cc14cf0969057a0f3447d708b753/pkg/kafka/client/writer_client.go#L173) are registered through [OnNewClient](https://github.com/grafana/loki/blob/18c9c05ee127e3c4a40cc885f08fd61a636dfc91/vendor/github.com/twmb/franz-go/plugin/kprom/kprom.go#L126) hook that gets triggered on client creation. This causes duplicate registration panic when we create more than one client

2024-12-30 18:16 UTC, owen-d approved these changes
I see; approved 👍

2024-12-30 18:35 UTC, merged