Labeladd
grafana/loki pull request #3468
Opened 2021-03-10 13:59 UTC by adityacs

**What this PR does / why we need it**:
Support `labelallow` stage in Promtail

**Checklist**
- [x] Documentation added
- [x] Tests updated

2021-03-10 14:35 UTC, adityacs commented on docs/sources/clients/promtail/stages/labelallow.md
> +- `kubernetes_controller_revision_hash`: `"774858987d"`
Do we need a better example?

2021-03-12 12:35 UTC, slim-bean requested changes
Thanks @adityacs this is great! could you also update the doc page which lists all the stages the _index.md file in the stages folder?

2021-03-12 17:24 UTC, adityacs commented
@slim-bean Updated `_index.md`

2021-03-17 13:04 UTC, slim-bean approved these changes
LGTM!

2021-03-17 13:04 UTC, merged