logcli: add support for bearer token authentication
grafana/loki pull request #3585
Opened 2021-04-07 15:39 UTC by dbluxo

**What this PR does / why we need it**:

Add support for basic token authentication in cases where the loki-queriers/frontends are exposed through a reverse proxy doing token/bearer authentication.

Based on closed PR: https://github.com/grafana/loki/pull/2889 Thanks @gcotone

**Which issue(s) this PR fixes**:
Fixes https://github.com/grafana/loki/issues/395 (Partially - it does not implement oauth2)

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-04-07 16:03 UTC, dbluxo commented
@achatterjee-grafana I saw that you reviewed the PR that this is based on. How can I request a review for this PR?

2021-04-09 14:22 UTC, achatterjee-grafana requested changes
Added some review comments.

2021-04-09 15:07 UTC, achatterjee-grafana requested changes
Found a few more.

2021-04-09 15:07 UTC, achatterjee-grafana commented on docs/sources/getting-started/logcli.md
> +      --bearer-token-file=""  adds the Authorization header Bearer to API requests for authentication purposes. Can also be set using LOKI_BEARER_TOKEN_FILE env var.
```suggestion
      --bearer-token-file=""  Add the Authorization header Bearer to API requests for authentication purposes. Can also be set using LOKI_BEARER_TOKEN_FILE env var.
```

2021-04-09 15:07 UTC, achatterjee-grafana commented on docs/sources/getting-started/logcli.md
> +      --org-id=""             adds X-Scope-OrgID to API requests for representing tenant ID. Useful for requesting tenant data when bypassing an auth gateway.
```suggestion
      --org-id=""             Add X-Scope-OrgID to API requests for representing tenant ID. Useful for requesting tenant data when bypassing an auth gateway.
```

2021-04-09 15:07 UTC, achatterjee-grafana commented on docs/sources/getting-started/logcli.md
> +      --analyze-labels        Printout a summary of labels including count of label value combinations, useful for debugging high cardinality series
```suggestion
      --analyze-labels        Prints out a summary of labels including the count of label value combinations, useful for debugging high cardinality series
```

2021-04-20 17:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=3585) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=3585) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=3585) it.</sub>

2021-04-22 16:56 UTC, achatterjee-grafana requested changes
Added some doc change requests.

2021-04-22 17:00 UTC, achatterjee-grafana requested changes
Some more.

2021-04-22 17:00 UTC, achatterjee-grafana commented on docs/sources/getting-started/logcli.md
> +    The "series" command will take the provided label matcher and return all the log streams found in the time window.
```suggestion
    The "series" command takes the label matcher (provided) and returns all the log streams found in the time window.
```

2021-04-22 17:00 UTC, achatterjee-grafana commented on docs/sources/getting-started/logcli.md
> +The "query" command will output extra information about the query and its results, such as the API URL, set of common labels, and set of excluded labels. This extra information can be suppressed with
```suggestion
The "query" command returns extra information about the query and its results, such as the API URL, a set of common labels, and a set of excluded labels. This extra information can be hidden with the --quiet flag.
```

2021-04-22 19:38 UTC, dbluxo commented on docs/sources/getting-started/logcli.md
> +  -o, --output=default        Specify output mode [default, raw, jsonl]. raw suppresses log labels and timestamp.
@achatterjee-grafana I don't understand the sense behind these improvements in the `getting-started/logcli.md`. This text is from the [source code](https://github.com/grafana/loki/blob/0a02aecdb993da9d56714d756a6be73039e5317d/cmd/logcli/main.go#L26), what is the point of changing it here?

2021-04-22 19:42 UTC, achatterjee-grafana commented
Feel free to ignore the doc change req. I did not realize this was for Loki

2021-04-27 07:26 UTC, dbluxo commented
What else can we do to move things forward here?

2021-04-29 15:46 UTC, dbluxo commented
@slim-bean Maybe you could please add a review request from loki-team again, it somehow got kicked out and I don't have rights to add it :-(

2021-05-19 18:27 UTC, dbluxo commented
There are conflicts in the meantime, I'm closing this PR and creating a new one with fewer doc changes as well.

2021-05-19 18:27 UTC, closed without merging