promtail: add support for TLS/mTLS in syslog receiver
grafana/loki pull request #3907
Opened 2021-06-25 17:55 UTC by johanfleury

**What this PR does / why we need it**:

Add support for TLS and mTLS in promtail's syslog receiver.

**Which issue(s) this PR fixes**:

Fixes #3898 

**Special notes for your reviewer**:

Go is not my main language (and I don’t really like it) so there might be some coding-style issue or some bad patterns.

I successfully tested this change using rsyslog and I got the following results:

* TLS disabled on both sides: works as before
* TLS enabled on both sides: works as before (with TCP sessions being encrypted)
* TLS enabled but client sends plain text messages: `level=warn ts=2021-06-25T17:34:09.985034229Z caller=syslogtarget.go:207 msg="error initializing syslog stream" err="tls: first record does not look like a TLS handshake"`
* TLS enabled with client verification, but client doesn’t send a certificate or send plain text messages: `level=warn ts=2021-06-25T17:28:22.787523967Z caller=syslogtarget.go:207 msg="error initializing syslog stream" err="tls: client didn't provide a certificate"`

**Checklist**:

- [x] Documentation added
- [ ] Tests updated

2021-06-25 17:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=3907) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=3907) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=3907) it.</sub>

2021-06-25 17:56 UTC, johanfleury commented on clients/pkg/promtail/targets/syslog/syslogtarget.go
> +	tlsEnabled := len(t.config.TLSConfig.CertFile) > 0 || len(t.config.TLSConfig.CertFile) > 0 || len(t.config.TLSConfig.CAFile) > 0
Not sure if this is the best way to check if `tls_config` is set.

2021-06-25 17:57 UTC, johanfleury commented on clients/pkg/promtail/targets/syslog/syslogtarget.go
> +func newTLSConfig(certFile string, keyFile string, caFile string) (*tls.Config, error) {
This is inspired by [NewTLSConfig from github.com/prometheus/common/config](https://pkg.go.dev/github.com/prometheus/common/config#NewTLSConfig).

2021-07-02 16:37 UTC, KMiller-Grafana requested changes
Spelling correction is needed in the Docs file. Otherwise, the docs portion of the PR looks good to me.

2021-07-02 16:37 UTC, KMiller-Grafana commented on docs/sources/clients/promtail/configuration.md
> +  # CA certificae used to validate client certificate (enables client certificate verification when set)
```suggestion
  # CA certificate used to validate client certificate. Enables client certificate verification when specified.
```

2021-07-03 16:26 UTC, johanfleury commented on docs/sources/clients/promtail/configuration.md
> +  # CA certificae used to validate client certificate (enables client certificate verification when set)
Fixed, thank you :)

2021-07-06 09:15 UTC, cyriltovena approved these changes
LGTM

2021-07-06 09:15 UTC, cyriltovena commented
@KMiller-Grafana I'll need your approval to merge this one please, thanks !

2021-07-06 20:56 UTC, KMiller-Grafana approved these changes
Thank you for the doc change.  Docs LGTM now.

2021-08-21 21:04 UTC, johanfleury commented
Can we merge this if everybody’s happy with it?

2021-09-22 14:14 UTC, johanfleury commented
These bots are awful.

2021-09-23 06:44 UTC, merged