Docs: add DynamoDB costs warning
grafana/loki pull request #3954
Opened 2021-07-07 08:23 UTC by Alex-Sizov

**What this PR does / why we need it**:
After we have switched Loki to DynamoDB we had a hefty check, because of a lot read/write requests to it. It wasn't covered by docs, so we wasn't aware that something like this could happen. 
I've added warning about possible costs of using Loki with DynamoDB.

**Special notes for your reviewer**:
All numbers I've got from our AWS billing console. And since we only introducing Loki there is no heavy usage of it.
There could be grammar errors, since I'm not a native speaker, but I've done my best)

2021-07-07 08:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=3954) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=3954) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=3954) it.</sub>

2021-07-08 17:11 UTC, KMiller-Grafana requested changes

2021-07-08 17:11 UTC, KMiller-Grafana commented on docs/sources/storage/_index.md
> +Using Loki with DynamoDB will not fit in AWS free tier because it need far more read/write operations (ReadCapacityUnit-Hrs and WriteCapacityUnit-Hrs in AWS terms) that is covered by it. Free tier co
No sub heading is needed here for this extra paragraph.

I'm suggesting a much more vague wording, as there are many factors that affect the quantity of DynamoDB R/W ops. So, we can suggest that our users pay attention, but we don't want to tell them what to do.

```suggestion
Be aware that the AWS pricing structure is based on quantities of read and write operations (AWS terminology: ReadCapacityUnit-Hrs and WriteCapacityUnit-Hrs). Consider monitoring your DynamoDB
operations, such that you can tune your installation.
```

2021-07-08 17:36 UTC, owen-d reviewed
Sorry about the surprise there. I think @KMiller-Grafana 's suggestions look good. @KMiller-Grafana perhaps we can emphasize a little more directly that the single store (boltdb-shipper) is the preferred method of running Loki and future development will be there. 

Here's where I was looking: https://github.com/grafana/loki/blame/main/docs/sources/storage/_index.md#L49

2021-08-12 18:01 UTC, owen-d commented
Going to close this due to inaction and because we'll be de-emphasizing all non-object storage backends in our docs soon.

2021-08-12 18:01 UTC, closed without merging