Docs: example about using azure storage account as storage
grafana/loki pull request #4152
Opened 2021-08-12 15:41 UTC by charles-woshicai

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2907 

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-08-12 17:15 UTC, KMiller-Grafana requested changes
Please make suggested changes.  Then, this documentation addition will LGTM.

2021-08-12 17:15 UTC, KMiller-Grafana commented on docs/sources/storage/_index.md
> +      container_name: xxx
Please use a different substitution than xxx, as the other examples in this section have done.

```suggestion
    azure:
      # For the account-key, see docs: https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal
      account_key: <account-key>
      # Your azure account name
      account_name: <account-name>
      # See https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#containers
      container_name: <container-name>
```

2021-08-16 21:09 UTC, KMiller-Grafana approved these changes
Thank you for making the changes. The docs LGTM now. Please take care of signing the CLA, such that we can merge these changes in.

2021-08-17 02:26 UTC, charles-woshicai commented
> Thank you for making the changes. The docs LGTM now. Please take care of signing the CLA, such that we can merge these changes in.

Done.

2021-08-19 15:30 UTC, owen-d approved these changes
Thanks!

2021-08-19 15:30 UTC, merged

2021-09-15 13:02 UTC, hterik commented
Hi
Being new to this, may i ask.

1. Why is request_timeout set to 0, when default value is 30.
It's easier to understand examples if they only contain the absolute minimum required configuration. If this deviation from the default is important, an explanation why would be good, and maybe in that case the default should be reconsidered.

2.  Why must the filesystem config be present?
It appears counter-inuitive that one has to add filesystem config when wanting to use azure.  Is this directory used for other temporary storage or is it a leftover from other config?

2022-04-21 13:12 UTC, thorker commented
I stumpled at the same points.
Can someone please explain these configurations?