docs:  (logs-deletion.md) URL Encode curl command
grafana/loki pull request #4294
Opened 2021-09-09 07:25 UTC by mr-karan

**What this PR does / why we need it**:

What: Update the `cURL` command example to URL encode
the `match` query param

Why: The current `cURL` command throws this error:

```
$ curl -X POST \                                                                                                                                        
  'http://localhost:3100/loki/api/admin/delete?match[]={foo="bar"}&start=1591616227&end=1591619692' \                                                    
  -H 'x-scope-orgid: fake'
1:4: parse error: unexpected "="
```

**Checklist**
- [x] Documentation added
- [ ] Tests updated

2021-09-09 07:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=4294) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=4294) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=4294) it.</sub>

2021-09-09 19:04 UTC, KMiller-Grafana requested changes

2021-09-10 16:13 UTC, mr-karan commented
@KMiller-Grafana Thanks for the review, made the suggested changes.

2021-09-10 18:04 UTC, merged

2021-09-17 09:39 UTC, Alan01252 commented
An alternative to this is to use -g

`
curl -g -X POST \
  'http://127.0.0.1:3100/loki/api/admin/delete?match[]={foo="bar"}&start=1591616227&end=1591619692' \
  -H 'x-scope-orgid: 1'
`

2021-09-17 11:25 UTC, mr-karan commented
Ah TIL. https://explainshell.com/explain?cmd=curl+-g

Yeah, this is a better option.