Do not run manifest and deploy jobs in cron.
grafana/loki pull request #4772
Opened 2021-11-17 13:55 UTC by jeschkies

2021-11-17 14:00 UTC, dannykopping requested changes

2021-11-19 10:17 UTC, dannykopping commented on .drone/drone.yml
> +  - pull_request
OK. Can you prevent `deploy` on the `pull_request` trigger please, at least?

2021-11-19 10:18 UTC, jeschkies commented on .drone/drone.yml
> +  - pull_request
Ah, ofc.

2021-11-24 07:30 UTC, dannykopping approved these changes
LGTM

2021-11-24 07:31 UTC, merged