Add SIG operator team to governance doc
grafana/loki pull request #4977
Opened 2021-12-20 14:24 UTC by periklis

**What this PR does / why we need it**:
This PR appends the SIG operator team to the official goverance doc as discussed here:
https://docs.google.com/document/d/1dSyDwUHpFdAjdS46X4RNx9OkewY2JimRWq3Xs39LScU/edit#

2022-01-05 07:23 UTC, cyriltovena approved these changes
LGTM on my side waiting for @RichiH to merge

2022-01-11 08:25 UTC, RichiH requested changes
LGTM including suggested cleanup.

2022-01-11 08:25 UTC, RichiH commented on docs/sources/community/governance.md
> +- **The Loki Operator sub-project**: The sum of all activities performed under this governance, concerning the repository subfolder `operator` or the community.
```suggestion
- **The Loki SIG (Special Interest Group) Operator**: The sum of all activities performed under this governance, concerning the repository subfolder `operator` or the community.
```

2022-01-11 08:25 UTC, RichiH commented on docs/sources/community/governance.md
> +The current SIG operator team members are:
```suggestion
The current Loki SIG Operator team members are:
```

2022-03-02 23:34 UTC, KMiller-Grafana commented
@RichiH Can you please re-review https://github.com/grafana/loki/pull/4977?

2022-04-16 07:01 UTC, RichiH approved these changes
LGTM

2022-04-16 07:01 UTC, merged