Improve docs on how to install logcli from source
grafana/loki pull request #5126
Opened 2022-01-13 07:59 UTC by chaudum

Closes #5108

Signed-off-by: Christian Haudum <christian.haudum@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

2022-01-13 08:29 UTC, kavirajk approved these changes
LGMT

2022-01-13 22:26 UTC, KMiller-Grafana requested changes

2022-01-13 22:26 UTC, KMiller-Grafana commented on docs/sources/getting-started/logcli.md
> +### Compile from source
```suggestion
### Build logcli from source
```

2022-01-13 22:26 UTC, KMiller-Grafana commented on docs/sources/getting-started/logcli.md
> +Clone Github repository and compile `logcli` from source:
```suggestion
Clone the Loki repository and build `logcli` from source:
```

2022-01-13 22:26 UTC, KMiller-Grafana commented on docs/sources/getting-started/logcli.md
> +cp cmd/logcli/logcli /usr/local/bin/logcli
```suggestion
```bash
git clone https://github.com/grafana/loki.git
cd loki
make logcli
```

Optionally, move the binary into a directory that is part of your `$PATH`:

```bash
cp cmd/logcli/logcli /usr/local/bin/logcli
```

2022-01-14 08:35 UTC, sandeepsukhani approved these changes
LGTM

2022-01-21 19:28 UTC, KMiller-Grafana approved these changes
Thanks for the changes.  LGTM.

2022-01-25 09:59 UTC, merged