Auto-expire old items from FIFO cache
grafana/loki pull request #5148
Opened 2022-01-14 15:30 UTC by chaudum

**What this PR does / why we need it**:

Addresses the problem of the FIFO cache where items become stale due to the validity setting but are never purged, as described in https://github.com/grafana/loki/issues/4921

**Which issue(s) this PR fixes**:
Fixes #4921

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

2022-01-17 07:12 UTC, cyriltovena commented on pkg/storage/chunk/cache/fifo_cache.go
> -	Validity     time.Duration `yaml:"validity"`
I think we have to deprecate it before deleting it.

This is because people having the value will not get their loki start.

2022-01-17 07:14 UTC, cyriltovena commented on pkg/storage/chunk/cache/fifo_cache.go
> -	Validity     time.Duration `yaml:"validity"`
ho nevermind I didn't realize you renamed also that one.

2022-01-17 13:05 UTC, cyriltovena approved these changes
LGTM

You should add a changelog entry.

2022-01-17 14:37 UTC, chaudum commented
@cyriltovena I've moved the ticker creation into the goroutine. Do you want to have another look?

2022-01-18 07:14 UTC, cyriltovena commented on pkg/storage/chunk/cache/fifo_cache.go
> +	ticker.Stop()
```suggestion
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-c.done:
			return
		case t := <-ticker.C:
			c.pruneExpiredItems(t, ttl)
		}
	}
	
```

2022-01-18 07:16 UTC, cyriltovena commented on pkg/storage/chunk/cache/fifo_cache.go
> +		if t.Sub(entry.updated) > ttl {
I think `t` can be late. Should we use now ?

2022-01-18 07:16 UTC, cyriltovena commented
> @cyriltovena I've moved the ticker creation into the goroutine. Do you want to have another look?

Let's wait for @KMiller-Grafana and I'll merge it.

2022-01-18 11:31 UTC, sandeepsukhani approved these changes
Nice work! LGTM modulo pending suggestions from Cyril.

2022-01-18 13:18 UTC, slim-bean commented
Very nice! thanks for adding this @chaudum!

2022-01-20 13:50 UTC, chaudum commented
Hey @KMiller-Grafana, could I get a review of the (small) docs changes I did on this PR so we can merge it?

2022-01-27 22:53 UTC, KMiller-Grafana requested changes
Small change suggestions.

2022-01-27 22:53 UTC, KMiller-Grafana commented on docs/sources/configuration/_index.md
> +  # The expiry duration for the cache; deprecated in favour of `-<prefix>.fifocache.ttl`.
This suggestion is made to attempt to match another deprecation notice on a configuration knob.

```suggestion
  # Deprecated: The expiry duration for the cache. Use `-<prefix>.fifocache.ttl`.
```

2022-01-27 22:53 UTC, KMiller-Grafana commented on docs/sources/configuration/_index.md
> +  # The time to live for items in the cache before they get purged.
```suggestion
  # The time for items to live in the cache before those items are purged.
```

2022-01-31 15:37 UTC, owen-d approved these changes

2022-01-31 15:38 UTC, merged