Add Grafana Labs SECURITY.md
grafana/loki pull request #5314
Opened 2022-02-03 13:13 UTC by RichiH

Signed-off-by: Richard Hartmann <richih@richih.org>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

2022-02-03 13:16 UTC, dannykopping approved these changes
LGTM, let's just wait for @KMiller-Grafana to review the prose.

2022-02-03 13:48 UTC, owen-d approved these changes

2022-02-07 23:17 UTC, KMiller-Grafana requested changes
My changes correct grammar and attempt to use present tense (as it is easier to understand).

2022-02-07 23:17 UTC, KMiller-Grafana commented on SECURITY.md
> +**Important:** We ask you to not disclose the vulnerability before it have been fixed and announced, unless you received a response from the Grafana Labs security team that you can do so.
```suggestion
**Important:** We ask that you not disclose the vulnerability before it has been fixed and announced, unless you receive a response from the Grafana Labs security team allowing you to disclose the vulnerability.
```

2022-02-07 23:17 UTC, KMiller-Grafana commented on SECURITY.md
> +where we will post a summary, remediation, and mitigation details for any patch containing security fixes.
```suggestion
We maintain [Security Announcements](https://community.grafana.com/c/support/security-announcements) on our community site,
where we post a summary, remediation, and mitigation details for any patch containing a security fix.
```

2022-02-07 23:17 UTC, KMiller-Grafana commented on SECURITY.md
> +Grafana Labs will send you a response indicating the next steps in handling your report. After the initial reply to your report, the security team will keep you informed of the progress towards a fix
```suggestion
Grafana Labs will respond, indicating the next steps in handling your report. After the initial reply to your report, the security team will keep you informed of the progress towards a fix and full announcement, and may ask for additional information or guidance.
```

2022-04-27 22:44 UTC, KMiller-Grafana requested changes

2022-04-27 22:44 UTC, KMiller-Grafana commented on SECURITY.md
> +If you think you have found a security vulnerability, please send a report to [security@grafana.com](mailto:security@grafana.com). This address can be used for all of Grafana Labs's open source and c
I don't know what was meant by the parenthetical "including but not limited to ... grafana.com" part of this paragraph.  "grafana.com" is not a commercial or open source product, so it does not make sense to me.  Perhaps "grafana.com" should be changed to something like "other products listed at grafana.com".

I'm including this suggestion such that you can see grammar corrections that should be changed.

```suggestion
If you think you have found a security vulnerability, please send a report to [security@grafana.com](mailto:security@grafana.com). This address can be used for all of Grafana Labs' open source and commercial products (including, but not limited to Grafana, Grafana Cloud, Grafana Enterprise, and grafana.com). We accept only vulnerability reports at this address.
```

2022-07-10 15:40 UTC, closed without merging