Run `make drone` to use the new build image
grafana/loki pull request #5368
Opened 2022-02-11 07:20 UTC by dannykopping

**What this PR does / why we need it**:
Updates the `.drone/.drone.yml` file after #5250 was merged.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

2022-02-11 07:44 UTC, jeschkies requested changes
🙏

2022-02-11 07:44 UTC, jeschkies commented on Makefile
>  BUILD_IMAGE_VERSION := 0.19.0
That should be 0.20.0 now. Thanks for taking this over.

2022-02-16 12:52 UTC, jeschkies commented
@dannykopping could you pull in my changes from https://github.com/jeschkies/loki/tree/danny/make-drone?

2022-02-16 13:10 UTC, dannykopping commented
> @dannykopping could you pull in my changes from https://github.com/jeschkies/loki/tree/danny/make-drone?

Done, and rebased against `main`

2022-02-16 13:44 UTC, jeschkies commented on .drone/drone.yml
> -name: loki-build-image
Why is this removed?

2022-02-16 15:33 UTC, jeschkies approved these changes

2022-02-16 15:33 UTC, merged