Docs: Warn ECS users to avoid plain text credentials
grafana/loki pull request #5387
Opened 2022-02-14 16:41 UTC by jrykr

**What this PR does / why we need it**:
- The current ECS example uses plain text configuration for `Url` with basic auth.
- When an ECS task is configured like this, then credentials are exposed in the task definition and in any version control for the configuration.
- This PR adds a note that indicates this is strictly to keep the example simple and provides links to the relevant AWS documentation for how to add sensitive data to log configuration.

**Which issue(s) this PR fixes**:
Fixes n/a

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

2022-02-14 16:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=5387) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=5387) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=5387) it.</sub>

2022-02-15 09:14 UTC, kavirajk approved these changes
Thanks @jrykr LGTM

2022-02-17 17:21 UTC, KMiller-Grafana requested changes

2022-02-17 17:21 UTC, KMiller-Grafana commented on docs/sources/clients/aws/ecs/_index.md
> +> We're including plain text credentials in `options` for simplicity. However, this exposes credentials in your ECS task definition and in any version controlled configuration. Instead, you should us
I don't see a need to make this a highlighted paragraph. 

```suggestion
We include plain text credentials in `options` for simplicity. However, this exposes credentials in your ECS task definition and in any version-controlled configuration. Mitigate this issue by using a secret store such as [AWS Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html), combined with the `secretOptions` configuration option for [injecting sensitive data in a log configuration](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html#secrets-logconfig).
```

2022-02-24 09:45 UTC, kavirajk commented
@KMiller-Grafana can you take a look again? Looks like @jrykr addressed your feedback

2022-04-28 22:00 UTC, closed without merging