[operator] Install operator in `openshift-operators-redhat` ns
grafana/loki pull request #5441
Opened 2022-02-22 03:50 UTC by sasagarw

**What this PR does / why we need it**:
- updates the default namespace for openshift to `openshift-operators-redhat`.
- updates the reference from `loki.openshift.io` -> `loki.grafana.com`

**Which issue(s) this PR fixes**:
Fixes #5440 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

2022-02-22 12:43 UTC, xperimental requested changes
Looks okay, only some minor changes.

While looking at the PR I came across the `--install-mode` which is currently set to `OwnNamespace`. Is this still correct when we plan to have the operator running in `openshift-operators-redhat` but Loki deployed to `openshift-logging`?

2022-02-22 13:42 UTC, sasagarw commented
@xperimental yeah it works fine when I try to deploy operator in `openshift-operators-redhat` and lokistack in `openshift-logging`. Didn't find any issue in running the complete stack.

2022-02-22 16:45 UTC, xperimental reviewed
Almost there, something just occurred to me while looking at it the second time: The later instructions in `hack_loki_operator.md` still correctly reference the `openshift-logging` namespace because we intend to run Loki in that namespace, but the first command referencing the namespace will fail if it does not exist.

Does it make sense to add a paragraph to the doc for creating the namespace before trying to add resources to it? In the document that would be before adding the AWS secret.

2022-02-23 12:06 UTC, xperimental approved these changes

2022-02-24 08:24 UTC, periklis approved these changes

2022-02-24 08:25 UTC, merged