operator: Updating addons
grafana/loki pull request #5599
Opened 2022-03-10 17:59 UTC by Red-GV

**What this PR does / why we need it**:
Updated the addons file to use `2.4.1` for promtail and logcli. Also configured the addons to work with the gateway and updated the documentation on how to use the addons.

**Which issue(s) this PR fixes**:
Fixes #5570

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

2022-03-11 09:33 UTC, periklis requested changes

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +rules:
This role is missing the policy to allow promtail push logs via the gateway:
```yaml
- apiGroups:
  - loki.grafana.com
  resources:
  - application
  resourceNames:
  - logs
  verbs:
  - create
```

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +    app.kubernetes.io/name: logcli
Can we expand the labels to something like:
```yaml                                                                                                                                                                                                                                                   
app.kubernetes.io/name=logcli
app.kubernetes.io/instance=developer-addons
```

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +  name: logcli-loki
Can we adapt the names to use a common prefix like `lokistack-dev-addons-`, e.g. `lokistack-dev-addons-logcli`

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +  name: logcli-loki-clusterrole
Name suggestion: `lokistack-dev-addons-reader`

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +  name: promtail-loki-clusterrole
Name suggestion: `lokistack-dev-addons-writer`

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +  name: logcli-loki-clusterrolebinding
Use the suggested name of the referenced ClusterRole.

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +  name: promtail-loki-clusterrolebinding
Use the suggested name of the referenced ClusterRole.

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +  name: promtail-loki
Name suggestion: `lokistack-dev-addons-promtail`

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +  name: logcli-loki
Name suggestion: `lokistack-dev-addons-logcli`

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +              value: http://lokistack-gateway-http-lokistack-dev.openshift-logging.svc:8080/api/logs/v1/application
With #5607 the new svc is `lokistack-dev-gateway-http` instead of `lokistack-gateway-http-lokistack-dev`

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +  name: promtail-loki
Name suggestion: `lokistack-dev-addons-promtail`

2022-03-11 09:33 UTC, periklis commented on operator/hack/addons.yaml
> +      - url: http://lokistack-gateway-http-lokistack-dev.openshift-logging.svc:8080/api/logs/v1/application/loki/api/v1/push
With #5607 the new svc is `lokistack-dev-gateway-http` instead of `lokistack-gateway-http-lokistack-dev`

2022-03-11 09:33 UTC, periklis commented on operator/docs/hack_loki_operator.md
> +kubectl apply -f hack\addons.yaml
Suggestion: `./hack/addons.yaml`

2022-03-15 17:08 UTC, xperimental reviewed
Two questions inline.

2022-03-18 08:11 UTC, periklis approved these changes

2022-03-18 08:11 UTC, merged