Fixed reader to support both authentication and tenant-id
grafana/loki pull request #5719
Opened 2022-03-28 18:03 UTC by kovaxur

**What this PR does / why we need it**:
Loki-canary will be able to use both basic-auth and x-scope-orgid headers.

**Which issue(s) this PR fixes**:
Fixes #5718 

**Special notes for your reviewer**:

**Checklist**
- [X] Documentation added
- [N/A] Tests updated
- [X] Add an entry in the `CHANGELOG.md` about the changes.

2022-03-28 18:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=5719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=5719) before we can accept your contribution.<br/><hr/>**Daniel Kovacs** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=5719) it.</sub>

2022-04-07 13:47 UTC, sandeepsukhani commented
It also won't work as is because the header setting you have changed is used just for live tailing. You also need to update `QueryCountOverTime` and `Query` functions below.

2022-04-20 22:10 UTC, KMiller-Grafana requested changes
2 tiny doc changes.

2022-04-20 22:10 UTC, KMiller-Grafana commented on docs/sources/operations/loki-canary.md
> +        Tenant id to be set in X-Scope-OrgID header.
```suggestion
        Tenant ID to be set in X-Scope-OrgID header.
```

2022-04-20 22:10 UTC, KMiller-Grafana commented on cmd/loki-canary/main.go
> +	tenantID := flag.String("tenant-id", "", "Tenant id to be set in X-Scope-OrgID header.")
```suggestion
	tenantID := flag.String("tenant-id", "", "Tenant ID to be set in X-Scope-OrgID header.")
```

2022-05-17 18:39 UTC, KMiller-Grafana approved these changes
From a Docs perspective, I approve this PR.

2022-05-18 09:03 UTC, sandeepsukhani approved these changes
LGTM

2022-05-18 09:03 UTC, merged