Docs: Document Promtail global rate limiting
grafana/loki pull request #5737
Opened 2022-03-31 17:41 UTC by KMiller-Grafana

Addresses issue https://github.com/grafana/loki/issues/5730.

Reviewers: what have I missed or gotten wrong in this addition of documentation?

2022-03-31 20:01 UTC, 09jvilla requested changes
Made one small suggestion - realize its a tad vague because I don't actually know the logic for how long it holds the lines back.

2022-03-31 20:01 UTC, 09jvilla commented on docs/sources/clients/promtail/configuration.md
> +# causes this instance of Promtail to hold off on sending the log lines.
```suggestion
# causes this instance of Promtail to temporarily hold off on sending the log lines and retry later.
```

2022-04-01 08:23 UTC, dannykopping commented on docs/sources/clients/promtail/configuration.md
> +## limit_config
This looks good @KMiller-Grafana, and we should align this with the flags registered here:
https://github.com/grafana/loki/blob/main/clients/pkg/promtail/limit/config.go#L14-L19

2022-04-02 06:12 UTC, dannykopping approved these changes
LGTM! Congrats on your first code change Karen :)

2022-04-02 07:50 UTC, liguozhong commented on docs/sources/clients/promtail/configuration.md
> +[limit_config: <limit_config>]
hi, thank you very much for the exquisite documentation, this PR changed the limit_config name

https://github.com/grafana/loki/pull/5707
Promtail: Rename config name limit_config to limits_config #5707

2022-04-04 05:12 UTC, 09jvilla requested changes
Looks good to me - I think all that's needed is making "limits" plural (revise from "limit")

2022-04-04 05:12 UTC, 09jvilla commented on docs/sources/clients/promtail/configuration.md
> +[limit_config: <limit_config>]
```suggestion
[limits_config: <limits_config>]
```

2022-04-04 05:12 UTC, 09jvilla commented on docs/sources/clients/promtail/configuration.md
> +## limit_config
```suggestion
## limits_config
```

2022-04-04 05:12 UTC, 09jvilla commented on docs/sources/clients/promtail/configuration.md
> +The optional `limit_config` block configures global limits for this instance of Promtail.
```suggestion
The optional `limits_config` block configures global limits for this instance of Promtail.
```

2022-04-04 22:03 UTC, 09jvilla approved these changes
LGTM!

2022-04-05 15:09 UTC, merged