Docs: Fix design docs index page
grafana/loki pull request #6008
Opened 2022-04-25 08:22 UTC by joanlopez

**What this PR does / why we need it**:

The [design docs index page](https://grafana.com/docs/loki/latest/design-documents/) is currently empty while there are some design docs available within that section. So, I thought it's good to have that index page as a shareable landing page for all the Loki design docs, which is technically valuable information.

2022-04-25 08:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=6008) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=6008) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=6008) it.</sub>

2022-05-03 21:06 UTC, KMiller-Grafana requested changes
Changing numbering to bullets, as there is no required ordering of steps here.

2022-05-03 21:06 UTC, KMiller-Grafana commented on docs/sources/design-documents/_index.md
> +1. [Ordering Constraint Removal](2021-01-ordering-constraint-removal/)
```suggestion
- [Labels from Logs](labels/)
- [Promtail Push API](2020-02-promtail-push-api/)
- [Write-Ahead Logs](2020-09-write-ahead-log/)
- [Ordering Constraint Removal](2021-01-ordering-constraint-removal/)
```

2022-05-04 18:35 UTC, KMiller-Grafana approved these changes
thanks for the changes.

2022-05-05 06:15 UTC, joanlopez commented
> thanks for the changes.

Thanks to you for your time on reviewing it! Feel free to merge it, although I belong to GL org, I don't seem to have merge permissions on this project.

2022-05-20 19:48 UTC, merged