operator: Add method to get authenticated from GCP
grafana/loki pull request #6125
Opened 2022-05-09 09:51 UTC by sasagarw

**What this PR does / why we need it**:
There isn't an authentication mechanism in the provided Loki configuration. The Loki GCS authentication is handled via the GCS SDK which is typically done with environment variables(For example:GOOGLE_APPLICATION_CREDENTIALS).

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-05-09 09:56 UTC, sasagarw commented
cc @periklis

2022-05-09 12:25 UTC, Red-GV reviewed
Looks overall fine to me. A small comment though.

2022-05-09 12:25 UTC, Red-GV commented on operator/internal/manifests/compactor.go
> +
Maybe this should just be a callable function in `var.go`? Similar to how we do the modifications for the service monitor?

2022-05-11 07:42 UTC, periklis requested changes

2022-05-11 07:42 UTC, periklis commented on operator/internal/manifests/var.go
> +	})
I suggest to continue using `mergo.Merge` for mutating manifests as we do in other places, e.g. [service monitor PKI](https://github.com/grafana/loki/blob/main/operator/internal/manifests/service_monitor.go#L136).

In addition I suggest we move the whole function out of `var.go` to `storage/configure.go` file and follow-up the configure pattern as in `gateway_tenants.go`, i.e.
- First in `storage/configure.go` you place the `ensureCredentialsFor GCS`
- Second in `manifests/object_storage.go` you place the switch based on `opts.Stack.Storage.Secret.Type`
- Third you call the `configureDeploymentForStorageType` and `configureStatefulSetForStorageType` only in the Builder functions (e.g. `BuildQuerier` w/o nesting if blocks in the original constructor functions (e.g. `NewQuerierDeployment`)

This ensures that we have dedicated configure/mutate functions with proper error handling (thanks to `mergo.Merge` while keeping our manifest constructors are pure and minimal as possible.

e.g.
```go
func configureDeploymentForStorageType(d *appsv1.Deployment, t lokiv1beta1.ObjectStorageType) error {
	switch t {
	case lokiv1beta1.ObjectStorageSecretGCS:
		return storage.ConfigureDeployment(d)
	default:
		return nil
	}
}
func configureStatefulSetForStorageType(d *appsv1.Deployment, t lokiv1beta1.ObjectStorageType) error {
	switch t {
	case lokiv1beta1.ObjectStorageSecretGCS:
		return storage.ConfigureStatefulSet(d)
	default:
		return nil
	}
}
```

2022-05-12 08:38 UTC, periklis approved these changes
Looks really good to me.

2022-05-12 11:22 UTC, merged