[docs] document logfmt pipeline stage
grafana/loki pull request #6238
Opened 2022-05-24 23:52 UTC by cstyan

I noticed earlier while writing a design doc that the `logfmt` pipeline stage is not documented. It was originally added here: https://github.com/grafana/loki/pull/4346

I've also fixed a minor typo in the json pipeline stage docs.

2022-05-25 08:36 UTC, kavirajk commented
@cstyan duplicate of this https://github.com/grafana/loki/pull/5921.

2022-06-09 06:06 UTC, cyriltovena approved these changes
LGTM

2022-07-25 18:32 UTC, DylanGuedes approved these changes
looks wonderful, lgtm!

2022-07-25 21:14 UTC, DylanGuedes requested changes
I reviewed it one more time after trying it better, I think now I have a few suggestions.

2022-07-25 21:14 UTC, DylanGuedes commented on docs/sources/clients/promtail/stages/logfmt.md
> +- logfmt:
Do you mind wrapping this logfmt inside a `pipeline_stages` key?

2022-07-25 21:14 UTC, DylanGuedes commented on docs/sources/clients/promtail/stages/logfmt.md
> +      unknown:
Do you mind using the `labels` stage in conjunction and adding a disclaimer telling that if not listed under `labels`, extracted labels are to be ignored?

2022-07-25 21:14 UTC, DylanGuedes commented on docs/sources/clients/promtail/stages/logfmt.md
> +title: logfmt
Do you mind adding `logfmt` to the list of existing stages in the stages page? (this one: https://grafana.com/docs/loki/latest/clients/promtail/pipelines/)

2022-07-25 21:51 UTC, KMiller-Grafana requested changes
Thanks for adding in this missing content!  A few suggestions for you.

2022-07-25 21:51 UTC, KMiller-Grafana commented on docs/sources/clients/promtail/stages/logfmt.md
> +# `logfmt` stage
As we add new content to the Loki documentation, we're trying to standardize what we include in the YAML front matter.  This suggestion adds 2 new fields to implement that.  I'm leaving out the weight field, as adding it only to this stage's file would mess up our (fine) alphabetized organization.

```suggestion
title: logfmt
menuTitle: logfmt
description: The logfmt parsing stage reads logfmt log lines and extracts the data into labels.
---
# `logfmt` stage
```

2022-07-25 21:51 UTC, KMiller-Grafana commented on docs/sources/clients/promtail/stages/logfmt.md
> +  # is empty then the logfmt field with the same name is extracted.
What do you think of being more explicit?
```suggestion
  # Set of key/value pairs for mapping of logfmt fields to extracted labels. The YAML key will be
  # the key in the extracted data, while the expression will be the YAML value. If the value
  # is empty, then the logfmt field with the same name is extracted.
```

2022-07-25 21:51 UTC, KMiller-Grafana commented on docs/sources/clients/promtail/stages/logfmt.md
> +If the value extracted is a complex type it's value is extracted as a string.
Just a bit of grammar and spelling suggestions.

```suggestion
This stage uses the [go-logfmt](https://github.com/go-logfmt/logfmt) unmarshaler, which means non-string types like
numbers or booleans will be unmarshaled into those types. The extracted data
can hold non-string values, and this stage does not do any type conversions;
downstream stages will need to perform correct type conversion of these values
as necessary. Please refer to the [`template` stage](../template/) for how
to do this.

If the value extracted is a complex type, its value is extracted as a string.
```

2022-07-25 21:51 UTC, KMiller-Grafana commented on docs/sources/clients/promtail/stages/logfmt.md
> +time=2012-11-01T22:08:41+00:00 app=loki level=WARN duration=125 message="this is a log line" extra="user=foo""
Is there an extra double quote mark at the end of this log line?  If yes, this suggestion removes it.
```suggestion
time=2012-11-01T22:08:41+00:00 app=loki level=WARN duration=125 message="this is a log line" extra="user=foo"
```

2022-08-29 14:12 UTC, DylanGuedes commented on docs/sources/clients/promtail/stages/logfmt.md
> +- logfmt:
agreed.

2022-08-29 14:40 UTC, merged