Fix Snyk Workflow/Troubleshooting
grafana/loki pull request #6280
Opened 2022-06-01 13:27 UTC by SadFaceSmith

**What this PR does / why we need it**:
Temp add error skipping while investigating Snyk instability
**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-06-01 20:30 UTC, MasslessParticle approved these changes

2022-06-02 20:09 UTC, MasslessParticle requested changes
`install snyk-to-html` is a place where a malicious PR could leak creds. We should take another approach where the action is in another repo and takes the secret as an input

2022-06-02 20:18 UTC, SadFaceSmith commented
Moved SNYK_TOKEN to env var instead of inline to the `snyk auth` command.

2022-06-02 20:54 UTC, SadFaceSmith commented
Closing in favor of centralized security-related GH Actions repo. Will reopen a PR in the future. Thanks for the help @MasslessParticle

2022-06-02 20:54 UTC, closed without merging