Loki: Return an __error_details__ label for any line which incurs a __error__ while being processed
grafana/loki pull request #6543
Opened 2022-06-29 14:50 UTC by slim-bean

**What this PR does / why we need it**:

Currently when Loki process a line, there are a numbe of reasons the processing won't go as expected, when this happens Loki sets an `__error__` label on each line that had issues, the value of this `__error__` label is one of several values e.g. JSONParserErr or TemplateFormatErr

Keeping the value of `__error__` to a simple set of values gives users granularity over removing only certain log lines with errors from a result, e.g. `__error__ != "TemplateFormatErr"`

However currently it's often difficult to understand why there was an error, rather than modify any existing behavior this PR introduces an additiona label `__error_details__` which contains more verbose error information with each line as to why the `__error__` label was set.

For example, perhaps you were trying to use a template function in your query `line_format "{{replace \"test\" .foo }}"`

This would set the `"__error__": "TemplateFormatErr"` in the response but doesn't give you a lot of understanding as to what went wrong.

Now in addition to that existing `__error__` label, Loki would also set this label:

`"__error_details__": "template: label:1:2: executing \"label\" at <replace>: wrong number of args for replace: want 3 got 2"`

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-06-29 15:20 UTC, MichelHollands approved these changes
LGTM

2022-06-29 20:14 UTC, owen-d approved these changes

2022-06-29 20:14 UTC, owen-d commented on pkg/logqlmodel/error.go
> +	ErrorDetailsLabel = "__error_details__"
LGTM

2022-06-29 21:12 UTC, chaudum requested changes
I think the function `func (b *LabelsBuilder) Reset()` also needs to reset the `errDetails`.

https://github.com/grafana/loki/blob/942d65935cc3537d98f963f21b95e0433e67fcbc/pkg/logql/log/labels.go#L132-L137

Otherwise all subsequent lines after an error have this label set.

2022-07-04 11:49 UTC, chaudum approved these changes

2022-07-18 18:14 UTC, merged