Draft of release notes for loki 2.6.
grafana/loki pull request #6546
Opened 2022-06-30 04:28 UTC by 09jvilla

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-06-30 18:27 UTC, KMiller-Grafana requested changes

2022-06-30 18:27 UTC, KMiller-Grafana commented on docs/sources/release-notes/v2-6.md
> +- **Support Baidu AI Cloud as a storage backend** Loki users can now use Baidu Object Storage (BOS) as their storage backend. See [bos_storage_config]({{< relref "../configuration/_index.md#bos_stora
Cosmetic changes suggested.

```suggestion
- **Query multiple tenants at once.** We've introduced cross-tenant query federation, which allows you to issue one query to multiple tenants and get a single, consolidated result. This is great for scenarios where you need a global view of logs within your multi-tenant cluster. For more information on how to enable this feature, see [Multi-Tenancy]({{< relref "../operations/multi-tenancy.md" >}}). 
- **Filter out and delete certain log lines from query results.** This is particularly useful in cases where users may accidentally write sensitive information to Loki that they do not want exposed. Users craft a LogQL query that selects the specific lines they're interested in, and then can choose to either filter out those lines from query results, or permanently delete them from Loki's storage. For more information, see [Logs Deletion]({{< relref "../operations/storage/logs-deletion.md" >}}).
- **Improved query performance on instant queries.** Loki now splits instant queries with a large time range (for example, `sum(rate({app="foo"}[6h]))`) into several smaller sub-queries and executes them in parallel. Users don't need to take any action to enjoy this performance improvement; however, they can adjust the number of sub-queries generated by modifying the `split_queries_by_interval` configuration parameter, which currently defaults to `30m`. 
- **Support Baidu AI Cloud as a storage backend.** Loki users can now use Baidu Object Storage (BOS) as their storage backend. See [bos_storage_config]({{< relref "../configuration/_index.md#bos_storage_config" >}}) for details. 
```

2022-06-30 18:27 UTC, KMiller-Grafana commented on docs/sources/release-notes/v2-6.md
> +- [PR 5888](https://github.com/grafana/loki/pull/5888) Fixed a bug in the [common configuration]({{< relref "../configuration/_index.md#common" >}}) where the `instance_inferace_names` setting was ge
```suggestion
- [PR 5685](https://github.com/grafana/loki/pull/5685) Fixed a bug in Loki's push request parser that allowed users to send arbitrary non-string data as a log line. We now test that the pushed values are valid strings and return an error if values are not valid strings.
- [PR 5799](https://github.com/grafana/loki/pull/5799) Fixed incorrect deduplication logic for cases where multiple log entries with the same timestamp exist. 
- [PR 5888](https://github.com/grafana/loki/pull/5888) Fixed a bug in the [common configuration]({{< relref "../configuration/_index.md#common" >}}) where the `instance_interface_names` setting was getting overwritten by the default ring configuration. 
```

2022-06-30 19:42 UTC, KMiller-Grafana approved these changes

2022-07-07 22:17 UTC, slim-bean approved these changes
LGTM!

2022-07-07 22:17 UTC, merged