Docs: Fix Helm Chart link
grafana/loki pull request #6985
Opened 2022-08-26 19:02 UTC by saerosV

**What this PR does / why we need it**:

- Fix the link pointing to a Loki Helm chart, found in the [Contribute to Helm](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md#contribute-to-helm) section of the [CONTRIBUTING.MD](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) file.
- Fix the link pointing to a Promtail Helm chart, found in the [Using Helm to deploy on Kubernetes](https://github.com/grafana/loki/blob/main/production/README.md#using-helm-to-deploy-on-kubernetes) section of the [production/README.md](https://github.com/grafana/loki/tree/main/production) file.

The previous links used were pointing to a [deprecated file](https://github.com/grafana/loki/tree/main/production/helm).

**Special notes for your reviewer**:

None.

**Checklist**
- [X] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-09-07 21:29 UTC, trevorwhitney requested changes
Given the recent migration of the helm chart back into this repo, I still think these links need to be updated, but to slightly different locations.

2022-09-07 21:29 UTC, trevorwhitney commented on CONTRIBUTING.md
> +Please follow the [Loki Helm Chart](https://github.com/grafana/helm-charts/blob/main/charts/loki/README.md#loki-helm-chart).
```suggestion
Please follow the [Loki Helm Chart](./production/helm/loki/README.md).
```

2022-09-07 21:29 UTC, trevorwhitney commented on production/README.md
> +- [Loki](https://github.com/grafana/helm-charts/blob/main/charts/loki/README.md#loki-helm-chart)
```suggestion
- [Loki](./production/helm/loki/README.md) 
```

2022-09-07 21:58 UTC, saerosV commented
@trevorwhitney Just updated the links, as per your suggestions. I think the PR is ready to be merged now. 

Thanks for the review!

2022-09-08 16:07 UTC, trevorwhitney approved these changes
lgtm, thanks for the fix!

2022-09-08 16:07 UTC, merged