Helm: Fix Prometheus rule LokiTooManyCompactorsRunning
grafana/loki pull request #7049
Opened 2022-09-05 06:54 UTC by calvinbui

Signed-off-by: Calvin Bui <3604363+calvinbui@users.noreply.github.com>

**What this PR does / why we need it**:

The Helm chart deploys two services, `loki` and `loki-headless`. 

The `loki_boltdb_shipper_compactor_running` metric will show all loki pods attached to both services.

The Prometheus rule in the chart, `LokiTooManyCompactorsRunning`,  does an aggregation over an entire namespace, which will always double the amount of compactors it detects.

![image](https://user-images.githubusercontent.com/3604363/188383102-192fc273-6a1f-469b-b87c-a10667a71946.png)

**Which issue(s) this PR fixes**:
Fixes N/A

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated
- [x] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-09-05 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=7049) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=7049) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=7049) it.</sub>

2022-09-05 06:56 UTC, calvinbui commented
CLA signed and chart version bumped

2022-09-05 07:34 UTC, kavirajk reviewed
LGTM. Thanks @calvinbui for the PR. Sounds reasonable to me. Leave it to @trevorwhitney  for final approval.

Added one minor suggestion to the changelog entry.

2022-09-05 07:34 UTC, kavirajk commented on production/helm/loki/CHANGELOG.md
> +- [BUGFIX] Fix Prometheus rule `LokiTooManyCompactorsRunning` aggregating multiple services together.
```suggestion
- [BUGFIX] Fix Prometheus rule `LokiTooManyCompactorsRunning` aggregating multiple services together in Loki helm chart.
```

Just to be more clear about, this is not changing the alerts for other environments like `tanka` and only for helm charts where we have `loki-headless`.

2022-09-06 00:32 UTC, calvinbui commented
On second thought, I'm not sure if this is the best approach as they'll be two alerts if it does go >1

2022-09-07 21:07 UTC, trevorwhitney requested changes
> On second thought, I'm not sure if this is the best approach as there'll be two alerts if it does go >1

Agreed. I think instead we should only scrape 1 of those services. My inclination would be to drop `loki-headless`, WDYT?

2022-09-11 23:37 UTC, calvinbui commented
> > On second thought, I'm not sure if this is the best approach as there'll be two alerts if it does go >1
> 
> Agreed. I think instead we should only scrape 1 of those services. My inclination would be to drop `loki-headless`, WDYT?

what about the simple-scalable services? they use -read and -write suffixed services

2022-09-20 13:02 UTC, varac commented
Hej, looking forward for this fix, what's the current state ?

2022-09-20 22:37 UTC, trevorwhitney commented
> what about the simple-scalable services? they use -read and -write suffixed services

yeah, good point, looks like maybe we want to always deploy the `loki` service (for both single binary and scalable topologies), and then we can just scrape this service and drop metrics from headless. WDYT?

2022-09-23 11:09 UTC, zarikx commented
If I'm not mistaken, `loki-headless` just needs `prometheus.io/service-monitor: "false"` label (similar to `service-read-headless` and `service-write-headless` services) to prevent discovering single-binary StatefulSet twice.

2022-09-25 23:27 UTC, calvinbui commented
> If I'm not mistaken, `loki-headless` just needs `prometheus.io/service-monitor: "false"` label (similar to `service-read-headless` and `service-write-headless` services) to prevent discovering single-binary StatefulSet twice.

agreed, the best solution. 

PR updated

2022-09-26 15:19 UTC, trevorwhitney approved these changes
lgtm! thanks!

2022-10-18 22:27 UTC, trevorwhitney commented
@calvinbui looks like this just needs a `helm-docs` update and it's good to go.

2022-10-21 16:05 UTC, trevorwhitney commented
@calvinbui looks like a markdown linting error?

2022-10-25 22:17 UTC, trevorwhitney commented
@calvinbui looks like all we need is one more rebase, a lot moving on the helm chart these past few days :smile: Thanks!

2022-10-31 22:11 UTC, calvinbui commented
😦😩

2022-10-31 22:11 UTC, closed without merging