Make gRPC connection timeout configurable
grafana/loki pull request #7464
Opened 2022-10-19 06:57 UTC by liguozhong

**What this PR does / why we need it**:
This PR attempts to add a grpc connection timeout so that loki's operator can have the opportunity to raise this timeout.

```
 server:
      grpc_server_connection_timeout: 600s
```
log
```
level=info ts=2022-10-17T06:28:23.653973829Z caller=handler.go:174 org_id=fake msg="slow query detected" method=GET host=loki-loki-distributed-query-frontend.loki-research-x4.svc.cluster.local:3100 path=/loki/api/v1/query_range time_taken=2m1.965813572s param_direction=backward param_end=1665987976954000000 param_limit=1000 param_query="{evtType=\"evt_ttsd\"} | json" param_start=1665966376954000000 param_step=10000ms
level=warn ts=2022-10-17T06:28:23.654024222Z caller=logging.go:86 traceID=55bbc9c1308e9842 orgID=fake msg="GET /loki/api/v1/query_range?direction=backward&end=1665987976954000000&limit=1000&query=%7BevtType%3D%22evt_ttsd%22%7D+%7C+json&start=1665966376954000000&step=10000ms (500) 2m1.9659356s Response: \"query index: rpc error: code = Unavailable desc = connection error: desc = \\\"transport: Error while dialing dial tcp 10.100.190.157:9095: i/o timeout\\\"\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: Grafana/9.1.5; "

level=error ts=2022-10-17T06:28:23.654071531Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="rpc error: code = Code(500) desc = query index: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.100.190.157:9095: i/o timeout\"\n"
```

 (500) 2m1.9659356s and connection error ... : i/o timeout .
I infer that grpc has connection timeout through 2m and connection timeout in the log.

https://github.com/weaveworks/common/pull/261
this PR having received some detailed review tips from @bboreham  in the weave/common project, this PR will provide an adjustable connection timeout in an attempt to solve a slack(https://grafana.slack.com/archives/CEPJRLQNL/p1665738667866879) user's problem. If this PR is valid, it will be fed back to the weave/common project.

This PR does not sure solve the timeout problem, so it is very likely that the PR will be rejected. 

The PR is only to invite more maintainers to notice the timeout problem, participate in the discussion, and give some suggestions to help users in slack.

**Which issue(s) this PR fixes**:
Fixes https://github.com/weaveworks/common/pull/261
https://grafana.slack.com/archives/CEPJRLQNL/p1665738667866879

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-10-20 08:06 UTC, chaudum reviewed
@liguozhong Do you think it would make sense to try to get the configuration option into `weaveworks/common/server`? @bboreham may help with that if you open a PR there. Would love to get his opinion.

2022-10-20 08:06 UTC, chaudum commented on pkg/server/server.go
> +	serverww "github.com/weaveworks/common/server"
Afaik, the import alias is not necessary here, even though the local package is named `server` as well. Functions/variables in this package are referenced without package name, though.

2022-10-20 08:37 UTC, liguozhong commented
> 

https://github.com/weaveworks/common/pull/261#issuecomment-1282341614

Before opening this PR. I've tried another PR in the weavework/common project. But generally, the 2m timeout time for metrics is long enough. Then log is not like this.

weavework/common doesn't just use by loki, so it's understandable for me to weavework/common reject this PR until I'm sure this parameter is valid.

However, loki's logql is usually relatively slow, and 2m timeout is usually not enough. In my loki cluster, the logql execution time is generally 5m to 10m.

2022-10-20 08:47 UTC, chaudum approved these changes
LGTM

2022-10-20 11:30 UTC, bboreham commented
I’m sorry I failed to convey my explanation. 

This is a _connection_ timeout. You would need a long connection timeout if your agent was on Mars. 

The fact that Loki can take minutes to run a query is irrelevant to the _connection_ timeout. Loki takes minutes to run a query _after_ the connection is made. 

I strongly recommend you focus your energies on figuring out what is actually going wrong.

2022-10-20 12:39 UTC, liguozhong commented
-- it is very likely that the PR will be rejected.

```
 (500) 2m1.9659356s
transport: Error while dialing dial tcp 10.100.190.157:9095: i/o timeout
```

This PR was rejected in another project before, and I understand that it is likely to be rejected this time. 

But how can we help users who are in difficulty in slack, I deduced from these two clues in the log, here I can determine that the connection timed out. What do these two lines of log mean and how to solve it. Have you had similar experience in the past?

2022-10-20 12:41 UTC, liguozhong commented
The PR is only to invite more maintainers to notice the timeout problem, participate in the discussion, and give some suggestions to help users in slack.

I believe at the moment this user is going through a torment and has a very bad impression of loki.

2022-10-24 05:29 UTC, liguozhong commented
`connection error: desc = \"transport: Error while dialing dial tcp 10.100.190.157:9095: i/o timeout`

10.100.190.157 is index-gateway ip. 
https://github.com/grafana/loki/pull/7497
maybe this pr can fix this issue.

If the index-gateway deadlocks, will the querier connect timeout?

2022-11-16 14:22 UTC, xutongd approved these changes

2022-11-16 14:23 UTC, xutongd requested changes
abcd

2022-11-17 12:42 UTC, bboreham commented
The server (process or machine, or perhaps network) is not responding. So the connection attempt times out.
Find out why it is not responding and fix that.

2022-11-17 12:48 UTC, liguozhong commented
If running in k8s, when the cpu limit of the pod is set too low, will the pod be suspended by docker continuously, resulting in grpc connect timeout

2022-11-17 14:54 UTC, bboreham commented
> If running in k8s, when the cpu limit of the pod is set too low, will the pod be suspended by docker continuously, resulting in grpc connect timeout

Yes, that could happen. Or if available memory is too low, if you have noisy neighbours, lots of things could cause it. 

(Technically it is Linux that suspends your process, not Docker. But your overall point stands)

2022-11-18 06:08 UTC, liguozhong commented
thanks

2022-11-18 06:08 UTC, closed without merging