Fix incorrect ingress paths when using single binary deployment
grafana/loki pull request #7530
Opened 2022-10-26 21:07 UTC by trevorwhitney

**What this PR does / why we need it**:
The helm ingress template was copied over from the simple scalable chart and does not work when deploying the chart in single binary configuration. This fixes that by adding a set of single binary routes, and conditionally configuring the ingress resource based on deployment type.

**Which issue(s) this PR fixes**:
Fixes #7080

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-10-26 21:10 UTC, trevorwhitney commented
@calvinbui would you mind double checking this works in your env since you filed the bug?

2022-10-27 15:36 UTC, jeschkies requested changes
Please merge `main` and generate the reference with `make -BC docs sources/installation/helm/reference.md`

2022-11-08 11:13 UTC, MichelHollands commented
@trevorwhitney This is looking good. Can you rebase and run the command Karsten mentioned? I can approve and merge afterwards.

2022-11-08 22:04 UTC, trevorwhitney commented
@jeschkies ran the command you mentioned and it nuked the reference.md, which I assume is not the goal?

2022-11-09 13:33 UTC, jeschkies commented
@trevorwhitney calling `BUILD_IN_CONTAINER=false make -BC docs sources/installation/helm/reference.md` from root dir should work.

2022-11-09 13:35 UTC, jeschkies commented
Here is the change for the reference https://github.com/trevorwhitney/loki/pull/1

2022-11-24 09:19 UTC, jeschkies approved these changes
Go Template is just super hard to read. I don't grasp the template completely but it seems mostly copy and paste.

2022-11-24 09:19 UTC, jeschkies commented on production/helm/loki/templates/_helpers.tpl
> +  ctx = . context
What is the context?

2022-11-24 09:19 UTC, merged