Only log flush error when there is one.
grafana/loki pull request #7953
Opened 2022-12-16 12:39 UTC by jeschkies

2022-12-16 12:53 UTC, MichelHollands approved these changes
LGTM

2022-12-16 13:17 UTC, dannykopping requested changes
This error message won't make much sense to the user; can we make it more clear what is the problem exactly?

2023-01-05 17:46 UTC, owen-d commented on pkg/util/log/log.go
> +	if err != nil {
This looks unnecessary as the first line of this `CheckFatal` function is
```
	if err == nil {
		return
	}
```

2023-01-05 17:47 UTC, owen-d commented
Closing, please reopen if I've missed something.

2023-01-05 17:47 UTC, closed without merging