Fix minio tokengen race
grafana/loki pull request #7985
Opened 2022-12-20 23:45 UTC by trevorwhitney

**What this PR does / why we need it**:

Removes MinIO from the loki helm chart. This was meant as a convenience, but there's currently no good way to determine the helm run order of jobs defined by the loki helm chart and those of the subchart. As a result, when using minio, it can often occur that the make buckets job doesn't run before the tokengen, which will cause the whole deployment to fail as the provisioner depends on the admin token generated in the tokengen job.

I think it's reasonable to expect people to bring their own object storage.

TODO: I need to update the docs to reflect this change.

**Special notes for your reviewer**:
This is built on https://github.com/grafana/loki/pull/7984 and includes changes from that PR.

**Checklist**
- [ ] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2022-12-21 14:21 UTC, jeschkies requested changes
This is awesome. It's a breaking change though. It should come with 4.0 of the Helm chart.

2022-12-21 14:21 UTC, jeschkies commented on tools/dev/k3d/Makefile
> +REGISTRY_PORT ?= $(or $(EXISTING_REGISTRY_PORT),46453)
That's been an issue on my side :slightly_smiling_face:

2022-12-21 14:21 UTC, jeschkies commented on tools/dev/k3d/environments/helm-cluster/README.md
> +This is a cluster designed for testing out helm charts. It is meant for running `helm install` against. It provides the required dependencies of the helm chart and nothing else (ie. minio is installe
```suggestion
This is a cluster designed for testing out Helm charts. It is meant for running `helm install` against. It provides the required dependencies of the Helm chart and nothing else (ie. minio is installed by the Helm chart). This differs from the other envs that, while also using the helm chart, use `tanka` to deploy those charts.
```

2022-12-21 14:21 UTC, jeschkies commented on tools/dev/k3d/environments/helm-cluster/main.jsonnet
> +  minio: helm.template('minio', '../../charts/minio', {
Could we have a values file instead? I'd love to document the steps without some automation.

2023-01-06 21:25 UTC, trevorwhitney commented
Replacing with https://github.com/grafana/loki/pull/8064, which fixes this problem without removing minio

2023-01-06 21:25 UTC, closed without merging