[Helm] Allow node port on single binary service
grafana/loki pull request #8166
Opened 2023-01-16 13:47 UTC by jkroepke

Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-01-17 17:45 UTC, sapslaj commented
Hey @jkroepke looks like we had the same idea. #8146 #8147

2023-01-18 22:55 UTC, trevorwhitney requested changes
Can you please provide a description and explain why you need this functionality? We are intentionally limiting what can be configured on the "internal" services.

2023-01-19 09:43 UTC, jkroepke commented
We have an central grafana instance (from loki perspective outside of the cluster) and we do not have flexibility of using ingress (we have only public ingress) and we do not want to expose loki to public internet.

The central grafana outside of the cluster needs direct access. node port is the easiest available option for us. In that case, the single binary loki "internal" service needs to be exposed to an other cluster.

2023-01-19 13:22 UTC, jkroepke commented
@trevorwhitney how to generate the docs?

> make -C docs sources/installation/helm/reference.md

generates no change

2023-01-19 18:27 UTC, MasslessParticle commented
@jkroepke This was an error on our end. We fixed it so a rebase should get this to pass. Sorry about that.

2023-01-24 23:02 UTC, trevorwhitney commented
As discussed in https://github.com/grafana/loki/pull/8147, enabling the gateway for single binary mode https://github.com/grafana/loki/issues/8269 will solve a few issues at once, while keeping the config smaller and different deployment modes more consistent. Closing in favor of that approach.

2023-01-24 23:02 UTC, closed without merging

2023-01-25 08:53 UTC, jkroepke commented
@trevorwhitney I'm bit confused, keeping the configuration small while integrate an automatic way to identity customer need feels like a conflict (https://github.com/grafana/loki/issues/8185)

2023-01-25 23:52 UTC, trevorwhitney commented
@jkroepke does my implementation clarify at all? https://github.com/grafana/loki/pull/8284. This requires no additional config (keeping it small), and only required the change of a single default value (which I believe was done in a non-breaking way). It does make it so the gateway is always enabled, but I feel like that's a good thing from a consistency perspective.