Helm - Loki: fix fullname for services
grafana/loki pull request #8234
Opened 2023-01-23 05:13 UTC by houqp

**What this PR does / why we need it**:

Loki services were created with the short name, but the ingress is referencing these services using the fullname.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-01-23 05:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/loki?pullRequest=8234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/loki?pullRequest=8234) before we can accept your contribution.<br/><hr/>**QP Hou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/loki?pullRequest=8234) it.</sub>

2023-01-23 12:49 UTC, jeschkies approved these changes

2023-01-24 22:47 UTC, trevorwhitney requested changes
How does this affect the included dashboards? I think this will affect the `job` label, and will break many of the dashboards, which are looking for `job=~"$namespace/(loki|enterprise-logs)-$target`. Instead let's fix the ingress.

2023-01-25 04:10 UTC, houqp commented
@trevorwhitney  should we fix the dashboards instead? The problem with the current setup being if you deploy multiple instances into the same namespace with different fullnames, it will result in conflicts. I do think this is a legitimate bug based on the variable name and what's in the ingress rule.

2023-01-25 18:31 UTC, trevorwhitney commented
> if you deploy multiple instances into the same namespace with different fullnames, it will result in conflicts

Is that a common use case? I wouldn't ever think to do that, and would use different namespaces.

That being said, I would very much welcome some better templating and compiling of the dashboards, but we may need to fix that upstream in the [mixin](https://github.com/grafana/loki/tree/main/production/loki-mixin) or improve the process by which we compile that mixin into the helm chart.

Currently those dashboards were just copied over from the compiled mixin, and a few things chnaged manually, but I don't think that's tenable long term, and have on my list to push the changes from https://github.com/grafana/loki/pull/8261 upstream back into the mixin. 

A better solution might be a job that compiles mixin at installation time so we can dynamically build the matcher? Or maybe we need to add something to our build pipeline that compiles the mixin with a templated matcher (ie `job="{{ .Release.namespace}}/{{ include 'loki.fullWriteName' }}`)?

2023-06-23 20:09 UTC, MasslessParticle commented
There's been no movement on this in 5 months. I'm going to close for inactivity

2023-06-23 20:09 UTC, closed without merging