Validate Loki timeouts align.
grafana/loki pull request #8354
Opened 2023-01-31 16:49 UTC by jeschkies

**What this PR does / why we need it**:
It should be impossible to define a server timeout that is smaller than the query timeout.

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-01-31 16:49 UTC, jeschkies commented on pkg/loki/loki.go
> +func ValidateConfigTimeouts(c *Config) error {
This should probably be moved to a different package. Maybe the validation package.

2023-02-10 14:19 UTC, DylanGuedes requested changes
nice catch, this looks solid. I know this is a draft, but since I was working on timeouts in the previous months I was curious :smile: 

my only concern is about interfering in the write timeout. The recently added per-tenant query-timeout doesn't affect it.

2023-02-10 14:19 UTC, DylanGuedes commented on pkg/loki/loki.go
> +		return fmt.Errorf("invalid read timeout, the server read timeout (%s) must be larger than the limits timeout (%s)", c.Server.HTTPServerReadTimeout, c.LimitsConfig.QueryTimeout)
```suggestion
		return fmt.Errorf("invalid read timeout, the server read timeout (%s) must be longer than the limits timeout (%s)", c.Server.HTTPServerReadTimeout, c.LimitsConfig.QueryTimeout)
```

2023-02-10 14:19 UTC, DylanGuedes commented on pkg/loki/loki.go
> +	if c.Server.HTTPServerWriteTimeout < time.Duration(c.LimitsConfig.QueryTimeout) {
not sure the write timeout has to be checked here. it shouldn't be affected by the query-timeout.

2023-02-10 14:19 UTC, DylanGuedes commented on pkg/loki/loki.go
> +		return fmt.Errorf("invalid write timeout, the server write timeout (%s) must be larger than the limtis timeout (%s)", c.Server.HTTPServerReadTimeout, c.LimitsConfig.QueryTimeout)
```suggestion
		return fmt.Errorf("invalid write timeout, the server write timeout (%s) must be longer than the limits timeout (%s)", c.Server.HTTPServerReadTimeout, c.LimitsConfig.QueryTimeout)
```

2023-02-10 14:19 UTC, DylanGuedes commented on pkg/validation/limits.go
> +	QueryTimeout               model.Duration `yaml:"query_timeout" json:"query_timeout" doc:"description=Timeout when querying backends (ingesters or storage) during the execution of\na query request.
ditto: the per-tenant query-timeout doesn't interfere with the write timeout

2023-04-17 10:04 UTC, closed without merging