Operator: Promote AlertingRules, RecordingRules and RulerConfig from v1beta1 to v1
grafana/loki pull request #8800
Opened 2023-03-14 18:07 UTC by aminesnow

**What this PR does / why we need it**:
This PR promotes the `AlertingRules`, `RecordingRules` and `RulerConfig` CRDs from `v1beta1` to `v1`.
A conversion `webhook` has been added.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-03-14 19:18 UTC, Red-GV reviewed
Think we also need to regenerate the docs for the api. Otherwise, lgtm.

2023-03-14 19:47 UTC, periklis reviewed
LGTM

2023-03-15 09:53 UTC, periklis requested changes

2023-03-15 09:53 UTC, periklis commented on operator/apis/loki/v1beta1/alertingrule_types.go
```suggestion
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
//+kubebuilder:unservedversion
```

2023-03-15 09:53 UTC, periklis commented on operator/apis/loki/v1beta1/recordingrule_types.go
>  //+kubebuilder:subresource:status
```suggestion
//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:unservedversion
```

2023-03-15 09:53 UTC, periklis commented on operator/apis/loki/v1beta1/rulerconfig_types.go
>  //+kubebuilder:subresource:status
```suggestion
//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:unservedversion
```

2023-03-15 10:48 UTC, periklis approved these changes

2023-03-15 10:48 UTC, merged