Expose optional label matcher for label values handler
grafana/loki pull request #8824
Opened 2023-03-16 21:35 UTC by periklis

**What this PR does / why we need it**:
This is a follow-up to expose the optional matchers on the labels values API to the HTTP handler introduced by #4933

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
Currently this works on the querier http API directly. However I still fail to pass the query from the frontend tripperware down the stack when request encoding happens. @jeschkies any advise welcome.

In addition I err to rename the parameter from `query` to `match`. However I hesitated to do so as per the `LokiLabelNamesRequest` implementing the `queryrangebase/Request` interface that in turns includes a `Query()` method.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-03-16 21:44 UTC, DylanGuedes requested changes

2023-03-16 21:44 UTC, DylanGuedes commented on pkg/logproto/logproto.proto
> +  string query = 5;
hmm don't you have to add the `gogoproto.nullable` to make it optional?

2023-03-16 21:44 UTC, DylanGuedes commented on pkg/querier/http.go
> +
```suggestion
```

2023-03-16 21:44 UTC, DylanGuedes commented on pkg/querier/queryrange/codec.go
> +		level.Info(util_log.Logger).Log("msg", "ENCODE CODEC", "name", request.GetPath(), "match", request.GetQuery())
```suggestion
```

2023-03-17 19:49 UTC, periklis commented on pkg/querier/queryrange/roundtrip.go
> +		level.Info(logutil.WithContext(req.Context(), r.logger)).Log("msg", "executing query", "type", "labels", "label", lr.Name, "length", lr.End.Sub(*lr.Start), "query", lr.Query)
@DylanGuedes I guess you may see this cause of Grafana Loki Enterprise code? ;)

2023-03-17 20:21 UTC, DylanGuedes commented on pkg/querier/queryrange/roundtrip.go
> +		level.Info(logutil.WithContext(req.Context(), r.logger)).Log("msg", "executing query", "type", "labels", "label", lr.Name, "length", lr.End.Sub(*lr.Start), "query", lr.Query)
haha it isn't, sorry for the confusion. the "executing query" log lines emitted on `pkg/logql` are the ones that have the query label. and actually, there's a "executing query" for the roundtrip that already have the `query` parameter, but that's for range queries.
anyway, resolved! :D

2023-03-18 20:28 UTC, periklis commented
@jeschkies @DylanGuedes Considering on how long we have #4933 in our code base remaining unexposed it may still be buggy returning duplicate label values when using a regex label matcher.

Assuming you use the k8s pod names as labels which are per se always unique, I want to filter the values for a set of namespaces I pass to labels values API via a regex matcher, e.g. 4 namespaces each 5 pods:

```
/loki/api/v1/label/kubernetes_pod_name/values?query={kubernetes_namespace_name=~"ns-a|ns-b|ns-c|ns-d"}
```

The resulting list includes duplicates (in total 25 pod names, of which 5 are duplicates):

```json
[
  "logger-57f5c5f65d-2wvh6",
  "logger-57f5c5f65d-4tm75",
  **"logger-57f5c5f65d-64pnf",**
  ** "logger-57f5c5f65d-64pnf",**
  "logger-57f5c5f65d-6kr2n",
  "logger-57f5c5f65d-7mpdb",
  "logger-57f5c5f65d-8lqng",
  "logger-57f5c5f65d-9njgp",
  "logger-57f5c5f65d-c5xv7",
  **"logger-57f5c5f65d-cbzpg",**
  **"logger-57f5c5f65d-cbzpg",**
  "logger-57f5c5f65d-dmw8k",
  "logger-57f5c5f65d-g658h",
  "logger-57f5c5f65d-kcvpm",
  "logger-57f5c5f65d-mfbmf",
  **"logger-57f5c5f65d-p2n5x",**
  **"logger-57f5c5f65d-p2n5x",**
  "logger-57f5c5f65d-q7h6d",
  **"logger-57f5c5f65d-r72wk",**
  **"logger-57f5c5f65d-r72wk",**
  "logger-57f5c5f65d-t8nlk",
  "logger-57f5c5f65d-t9tl9",
  **"logger-57f5c5f65d-ttkkh",**
  **"logger-57f5c5f65d-ttkkh",**
  "logger-57f5c5f65d-wj6lj"
]
```

I have tried to debug this adding some matchers tests in f8ee569c5dde130a948b5180fa46a41b302636ef for the `series_index_store`. However it looks the stores work fine for every schema and config so far. Any clue what could cause such a behavior? (maybe missing dedup work on the query frontend?)

2023-03-20 15:28 UTC, aminesnow commented on pkg/querier/queryrange/codec_test.go
> +	// require.Equal(t, fmt.Sprintf("%d", end.UnixNano()), got.URL.Query().Get("end"))
What's up with commented lines? Is this WIP?

2023-03-21 09:12 UTC, jeschkies commented on pkg/ingester/ingester.go
> +	if req.Query != "" {
Looks good I'm first sight t I'm wondering if it should be called `matchers`. I'm also widening if we have a different way to serialize them. I'll check.

2023-03-21 09:41 UTC, jeschkies commented on pkg/logproto/logproto.proto
> +  string query = 5;
So we use this proto somewhere internally

```protobuf

enum LabelMatcherType {
  LABEL_MATCHER_TYPE_UNSPECIFIED  = 0;
  LABEL_MATCHER_TYPE_EQ  = 1;
  LABEL_MATCHER_TYPE_NEQ = 2;
  LABEL_MATCHER_TYPE_RE  = 3;
  LABEL_MATCHER_TYPE_NRE = 4;
}

message LabelMatcher {
  LabelMatcherType type    = 1;
  string name  = 2;
  string value = 3;
};
```

And convert it to `labels.Matcher`. I'm not sure this is worthwhile.

2023-03-21 09:41 UTC, jeschkies commented on pkg/ingester/ingester.go
> +	if req.Query != "" {
Well, here is your answer for me

> However I hesitated to do so as per the LokiLabelNamesRequest implementing the queryrangebase/Request interface that in turns includes a Query() method.

Could you add this as a comment to the proto?

2023-03-21 18:45 UTC, periklis commented on docs/sources/api/_index.md
> +- `query`: A set of log stream selector that selects the streams to match and return label values for `<name>`.
@aminesnow What Prometheus calls a label set, we call a set of log stream selectors in Loki: https://grafana.com/docs/loki/next/logql/log_queries/#log-stream-selector

2023-03-21 18:48 UTC, aminesnow commented on docs/sources/api/_index.md
> +- `query`: A set of log stream selector that selects the streams to match and return label values for `<name>`.
Yeah I know, I was just pointing out the typo, ie the missing S at the end of `selector`. Sorry for the miss understanding :sweat_smile:

2023-03-21 18:52 UTC, periklis commented on docs/sources/api/_index.md
> +- `query`: A set of log stream selector that selects the streams to match and return label values for `<name>`.
No worries, using the suggestions feature make such things more visible though ;)

2023-03-22 17:16 UTC, JStickler commented
[docs team]  So, looking at both this PR and #4933, and there's just a single line of new documentation?  I feel like this needs more doc.

2023-03-30 11:39 UTC, jeschkies commented on pkg/logproto/logproto.proto
> +  string query = 5;
I think you'd have to add another call which might be too much work.

2023-03-30 11:47 UTC, jeschkies reviewed
I've got a few tiny open questions. Otherwise it looks good.

As for your error. Do you get duplicates without passing label marchers?

2023-03-30 11:47 UTC, jeschkies commented on pkg/querier/queryrange/roundtrip.go
> +		// queryrangebase.InstrumentMiddleware("split_by_interval", metrics.InstrumentMiddlewareMetrics),
I think this should be activated again.

2023-03-30 11:47 UTC, jeschkies commented on pkg/querier/queryrange/stats.go
> +		logql.RecordLabelQueryMetrics(data.ctx, logger, data.params.Start(), data.params.End(), data.label, strings.Join(data.match, ","), data.status, *data.statistics)
Could we edit `queryData` instead of using the `match` field?

2023-03-30 12:32 UTC, jeschkies commented on pkg/querier/queryrange/stats.go
> +					data.match = []string{r.GetQuery()}
Is this still required?

2023-03-30 12:37 UTC, periklis commented on pkg/querier/queryrange/stats.go
> +					data.match = []string{r.GetQuery()}
No, that's a good catch!

2023-03-30 12:40 UTC, jeschkies approved these changes

2023-03-30 12:47 UTC, DylanGuedes approved these changes
lgtm, just a few nits

2023-03-30 12:47 UTC, DylanGuedes commented on pkg/logproto/logproto.proto
> +  string query = 5; // Naming this query instead of match because this is should be with queryrangebase.Request interface
```suggestion
  string query = 5; // Naming this query instead of match because this should be with queryrangebase.Request interface
```

2023-03-30 12:47 UTC, DylanGuedes commented on pkg/querier/queryrange/codec_test.go
> +	// require.Equal(t, "", req.(*LokiLabelNamesRequest).EndTs)
```suggestion
	require.Equal(t, "toEncode.StartTs", req.(*LokiLabelNamesRequest).StartTs)
	require.Equal(t, "", req.(*LokiLabelNamesRequest).EndTs)
```

2023-03-30 12:47 UTC, DylanGuedes commented on docs/sources/api/_index.md
> +- `query`: A set of log stream selector that selects the streams to match and return label values for `<name>`.
Nit: WDYT of adding a small example here so end users know what this syntax looks like?
```suggestion
- `query`: A set of log stream selector that selects the streams to match and return label values for `<name>`. Example: `{"app": "myapp", "environment": "dev"}`
```

2023-03-30 13:26 UTC, merged