[opt] querier-frontend: downstream exe fail, add detail error msg and test
grafana/loki pull request #8864
Opened 2023-03-22 02:46 UTC by liguozhong

**What this PR does / why we need it**:
return detail error msg when downstream exe fail and add test.

**Which issue(s) this PR fixes**:
Fixes #8844

**Special notes for your reviewer**:
![image](https://user-images.githubusercontent.com/9583245/226788711-65f4249f-bde6-465c-90de-ac825f6013d9.png)

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-03-22 06:49 UTC, dannykopping reviewed
LGTM but shouldn't we also add handlers for the two cases `*syntax.BinOpExpr` and *syntax.VectorAggregationExpr` that you point out?

2023-03-22 06:49 UTC, dannykopping commented on pkg/logql/downstream.go
> +			return nil, fmt.Errorf("downstream evaluator fail to execute default case, expr type: %s ,logql: %s , err: %s", reflect.TypeOf(e), e.String(), err)
```suggestion
			return nil, fmt.Errorf("downstream evaluator fail to execute default case, expr type: %T, logql: %s , err: %s", e, e, err)
```

2023-03-22 06:49 UTC, dannykopping commented on pkg/logql/downstream_test.go
> +		{logqlCase1, fmt.Errorf("downstream evaluator fail to execute default case, expr type: %s ", reflect.TypeOf(&syntax.BinOpExpr{}))},
```suggestion
		{logqlCase1, fmt.Errorf("downstream evaluator fail to execute default case, expr type: %T ", &syntax.BinOpExpr{})},
```

2023-03-22 07:29 UTC, liguozhong commented
> LGTM but shouldn't we also add handlers for the two cases `*syntax.BinOpExpr` and *syntax.VectorAggregationExpr` that you point out?

I'm not very familiar with downstream.go and I need a little time to understand how this works so that I can write more Expr handlers properly. My suggestion is to support more Expr handler cases in another PR

2023-03-22 18:07 UTC, DylanGuedes requested changes

2023-03-22 18:07 UTC, DylanGuedes commented on pkg/logql/downstream.go
> +			return nil, fmt.Errorf("downstream evaluator fail to execute default case, expr type: %T , logql: %s , err: %s", e, e, err)
```suggestion
			return nil, fmt.Errorf("downstream evaluator fail to execute default case, expr type: %T , logql: %s , err: %w", e, e, err)
```

2023-03-22 18:07 UTC, DylanGuedes commented on pkg/logql/downstream.go
> +			return nil, fmt.Errorf("downstream evaluator fail to execute default case, expr type: %T , logql: %s , err: %s", e, e, err)
you used `e` for both, type and logql

2023-03-22 18:07 UTC, DylanGuedes commented on pkg/logql/downstream_test.go
> +
```suggestion
```

2026-09-22 08:04 UTC, chaudum commented
The PR is out-of-date and the "missing" detailed error message hasn't been a problem, so closing this.

2026-09-22 08:04 UTC, closed without merging