Steven 2 8 docs
grafana/loki pull request #9021
Opened 2023-04-04 20:50 UTC by stevendungan

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-04-04 20:52 UTC, DylanGuedes approved these changes, later dismissed

2023-04-04 20:54 UTC, DylanGuedes requested changes

2023-04-04 20:54 UTC, DylanGuedes commented on docs/sources/release-notes/v2-8.md
>  - **Query blocker** Queries can now be blocked in the Querier/Ruler via a per-tenant runtime configuration.
this isn't on 2.8 btw

2023-04-04 21:00 UTC, DylanGuedes requested changes

2023-04-05 20:09 UTC, trevorwhitney commented
@stevendungan can we close this?

2023-05-05 06:58 UTC, dannykopping commented
@stevendungan bump, is this still needed?

2023-06-23 20:55 UTC, closed without merging