operator: Add a PodDisruptionBudget to Loki Operator Gateway
grafana/loki pull request #9162
Opened 2023-04-17 15:35 UTC by aminesnow

**What this PR does / why we need it**:
This PR adds a `PodDisruptionBudget` to the Loki Operator Gateway, with a `MinAvailable` of 1.

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-04-17 18:41 UTC, periklis approved these changes
Just nits

2023-04-17 18:41 UTC, periklis commented on operator/CHANGELOG.md
> +- [9162](https://github.com/grafana/loki/pull/9162) **aminesnow**: Add a PodDisruptionBudget to Loki Operator Gateway
```suggestion
- [9162](https://github.com/grafana/loki/pull/9162) **aminesnow**: Add a PodDisruptionBudget to lokistack-gateway
```

2023-04-17 18:42 UTC, periklis requested changes
Doesn't that need to run `make bundle-all`?

2023-04-18 07:58 UTC, aminesnow commented
> Doesn't that need to run `make bundle-all`?

Yes it does.

2023-04-18 12:48 UTC, periklis approved these changes

2023-04-18 12:49 UTC, merged