Loki microservices Tanka: fix error during manifest generation
grafana/loki pull request #9362
Opened 2023-05-02 07:51 UTC by irizzant

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #9361 

This PR fixes an error with the ServiceMonitor generated when
```
memberlist_ring_enabled: true,
create_service_monitor: true,
```
It also adds some checks on `memberlist.libsonnet` to avoid generating invalid kubernetes manifests.

**Special notes for your reviewer**:

**Checklist**
- [X] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [X] Documentation added
- [X] Tests updated
- [X] `CHANGELOG.md` updated
- [X] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-05-02 07:57 UTC, irizzant commented
@DylanGuedes again? ;)

2023-05-02 09:47 UTC, DylanGuedes requested changes
Thanks for your contribution! Added a question

2023-05-02 09:47 UTC, DylanGuedes commented on production/ksonnet/loki/servicemonitor.libsonnet
> +            if std.isObject(this[name]) && std.objectHas(this[name], 'kind') && this[name].kind == 'Service' && std.objectHasAll(this[name].spec.selector, 'name')
could you confirm if it shouldn't be `name` instead of `'name'`?

2023-05-04 07:07 UTC, irizzant commented
@DylanGuedes do you need anything else for this to be merged?

2023-05-04 09:15 UTC, DylanGuedes commented
> @DylanGuedes do you need anything else for this to be merged?

i asked you [this question](https://github.com/grafana/loki/pull/9362#discussion_r1182331878).

2023-05-04 10:10 UTC, irizzant commented
@DylanGuedes sorry I thought you saw this reply:
![image](https://user-images.githubusercontent.com/15982257/236175406-dcdc7e4e-91ab-42ab-ad33-9751b74fca3c.png)

2023-05-04 10:22 UTC, DylanGuedes commented
> @DylanGuedes sorry I thought you saw this reply: ![image](https://user-images.githubusercontent.com/15982257/236175406-dcdc7e4e-91ab-42ab-ad33-9751b74fca3c.png)

it won't show up for me because it is pending :rofl: anyway, approved

2023-05-04 10:23 UTC, merged