operator: add zone aware API spec validation
grafana/loki pull request #9378
Opened 2023-05-03 09:58 UTC by aminesnow

**What this PR does / why we need it**:
Following #9315, this PR adds validation to the zones awareness spec of the `LokiStack` API. 

**Special notes for your reviewer**:
@periklis 

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-05-04 11:34 UTC, xperimental reviewed
In general, I don't know if this validation is a good idea, because it might hinder the admin to make changes to a malfunctioning cluster as, depending on the failure, the list of nodes might not contain all the "normally available values" then.

In my opinion, the validation should only fail on configurations which "will absolutely never work" and not depend on the current state.

2023-05-04 11:34 UTC, xperimental commented on operator/internal/validation/lokistack.go
> +	Client            client.Client
I think you should move `Client` above `ExtendedValidator` as the extended validation is optional, but the client is not.

2023-05-08 08:17 UTC, periklis requested changes
After digging a bit into the k8s docs, I suggest to take a different course of action here, since `PodTopologyConstraints` solving the issue for node labels internally offering the configuration option `minDomains` (See https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition):

```
minDomains indicates a minimum number of eligible domains. This field is optional. A domain is a particular instance of a topology. An eligible domain is a domain whose nodes match the node selector.
```

WDYT?

2023-05-09 08:46 UTC, aminesnow commented
> After digging a bit into the k8s docs, I suggest to take a different course of action here, since `PodTopologyConstraints` solving the issue for node labels internally offering the configuration option `minDomains` (See https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition):
> 
> ```
> minDomains indicates a minimum number of eligible domains. This field is optional. A domain is a particular instance of a topology. An eligible domain is a domain whose nodes match the node selector.
> ```
> 
> WDYT?

Interestintg find. Will give it a look and see how that goes.
Btw, should we be worried about this: `minDomains field is a beta field and disabled by default in 1.25.`?

2023-05-11 07:13 UTC, periklis approved these changes

2023-05-11 07:13 UTC, periklis commented on operator/apis/loki/v1/lokistack_types.go
> +	// IMPORTANT: Make sure that the replication factor defined is less than the number of available zones.
Is it strictly required to be "less" or can it be also "less or equal"

2023-05-15 13:40 UTC, JStickler approved these changes
[Docs team]  Approving, since it looks like this is just adding the validation and the API is documented by #9315.

2023-05-17 04:40 UTC, periklis reviewed
LGTM, let's update the branch to keep in sync with generated files.

2023-05-17 12:44 UTC, merged