Add default PodAntiAffinity to Query-Frontend
grafana/loki pull request #9383
Opened 2023-05-03 10:54 UTC by JoaoBraveCoding

Issue: https://issues.redhat.com/browse/LOG-3850

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [x] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

2023-05-05 09:25 UTC, aminesnow requested changes
One change request, otherwise LGTM!

2023-05-05 09:25 UTC, aminesnow commented on operator/internal/manifests/var.go
> +		kubernetesComponentLabel: l[kubernetesComponentLabel],
It's much better to have the signature be very clear than use a map for parameters.
```suggestion
func componentInstaceLabels(component string, stackName string) map[string]string {
	return map[string]string{
	        kubernetesInstanceLabel:  stackName,
		kubernetesCompomentLabel: component,
					
```

2023-05-05 09:25 UTC, aminesnow commented on operator/CHANGELOG.md
> +- [9383](https://github.com/grafana/loki/pull/9383) **JoaoBraveCoding**: Add default TopologySpreadContaints to Distributor
```suggestion
- [9383](https://github.com/grafana/loki/pull/9383) **JoaoBraveCoding**: Add default TopologySpreadContaints to Distributor
- [9366](https://github.com/grafana/loki/pull/9366) **periklis**: Add support for custom tenant topology in rules
```

2023-05-08 08:40 UTC, periklis requested changes

2023-05-08 08:40 UTC, periklis commented on operator/internal/manifests/distributor.go
> +		TopologySpreadConstraints: defaultTopologySpreadConstraints(l),
This definition is overwritten by and thus no node-spreading is happening when zone-aware data replication is on. See:
https://github.com/grafana/loki/blob/520e434446e4c646ecc2678f3c3b57fff69643cc/operator/internal/manifests/var.go#L146-L166

2023-05-08 10:39 UTC, periklis requested changes

2023-05-08 10:39 UTC, periklis commented on operator/CHANGELOG.md
> +- [9383](https://github.com/grafana/loki/pull/9383) **JoaoBraveCoding**: Add default TopologySpreadContaints to Distributor
```suggestion
- [9383](https://github.com/grafana/loki/pull/9383) **JoaoBraveCoding**: Add default TopologySpreadContaints to Distributor
- [9406](https://github.com/grafana/loki/pull/9406) **aminesnow**: Add label selector to zone awareness TopologySpreadConstraints
```

2023-05-08 10:39 UTC, periklis commented on operator/internal/manifests/var.go
> +						kubernetesComponinternal/manifests/distributor_test.goentLabel: component,
Edit typo?

2023-05-08 10:54 UTC, periklis approved these changes

2023-05-08 10:54 UTC, merged