add shards to querystats bytes processed
grafana/loki pull request #9934
Opened 2023-07-13 17:16 UTC by trevorwhitney

This adds a shards label to the `loki_logql_querystats_bytes_processed_per_second` metric that we use for determining our `LokiQueryRangeReadPerformanceBudgetBurn` metric so we can exclude slow queries with 0 shards from burning our SLO budget.

WDYT?

2023-07-14 07:41 UTC, chaudum commented
> WDYT?

What is the potential cardinality of the `shards` label?

2023-07-14 18:52 UTC, trevorwhitney commented
@chaudum that's a good point, it's bounded by the number of shards which could be in the thousands. What if we converted this to a boolean, as we really only care about `0 shards` or `> 0 shards`?

2023-07-14 19:41 UTC, trevorwhitney commented
I'm thinking `shardable=[true|false]`

2023-07-17 19:28 UTC, DylanGuedes requested changes

2023-07-17 19:28 UTC, DylanGuedes commented on pkg/logql/metrics.go
> -	bytesPerSecond.WithLabelValues(status, queryType, "", latencyType).
doesn't that mean that this metric can have infinite cardinality?

2023-07-17 19:48 UTC, owen-d commented
Make it `sharded=true|false` because shardable queries that touch less than 1 shard's maximum size will be executed unsharded.

2023-07-18 16:54 UTC, trevorwhitney commented
I have changed the label to a boolean, with the logic being 0 or 1 shards is `sharded=false`, while > 1 shards is `sharded=true`. There are a few places in the code we check if shards are 0 and if so set them to 1, so it seemed like we'd what to capture both cases for "non-sharded".

2023-07-18 17:15 UTC, DylanGuedes requested changes

2023-07-18 17:15 UTC, DylanGuedes commented on pkg/logql/metrics.go
> +		"sharded", stats.Summary.Shards,
```suggestion
		"shards", stats.Summary.Shards,
```

2023-07-18 18:31 UTC, trevorwhitney commented on pkg/logql/metrics.go
> +		"sharded", stats.Summary.Shards,
sloppy rename... thank you!

2023-07-18 18:40 UTC, DylanGuedes approved these changes

2023-07-19 22:47 UTC, merged